(()=>{var io=Object.create;var At=Object.defineProperty;var ao=Object.getOwnPropertyDescriptor;var co=Object.getOwnPropertyNames;var lo=Object.getPrototypeOf,fo=Object.prototype.hasOwnProperty;var cr=(e,t)=>()=>(e&&(t=e(e=0)),t);var lr=(e,t)=>()=>(t||e((t={exports:{}}).exports,t),t.exports),uo=(e,t)=>{for(var r in t)At(e,r,{get:t[r],enumerable:!0})},po=(e,t,r,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let o of co(t))!fo.call(e,o)&&o!==r&&At(e,o,{get:()=>t[o],enumerable:!(n=ao(t,o))||n.enumerable});return e};var fr=(e,t,r)=>(r=e!=null?io(lo(e)):{},po(t||!e||!e.__esModule?At(r,"default",{value:e,enumerable:!0}):r,e));var m,d=cr(()=>{m={env:{NODE_ENV:"production",LOG_LEVEL:"warn"},browser:!0,version:"",stdout:null,stderr:null,nextTick:function(e){var t=Array.prototype.slice.call(arguments,1);Promise.resolve().then(function(){e.apply(null,t)})}}});var bn=lr((Ia,yn)=>{d();yn.exports={}});var vn=lr(Be=>{"use strict";d();Object.defineProperty(Be,"__esModule",{value:!0});Be.bech32m=Be.bech32=void 0;var ft="qpzry9x8gf2tvdw0s3jn54khce6mua7l",wn={};for(let e=0;e<ft.length;e++){let t=ft.charAt(e);wn[t]=e}function Se(e){let t=e>>25;return(e&33554431)<<5^-(t>>0&1)&996825010^-(t>>1&1)&642813549^-(t>>2&1)&513874426^-(t>>3&1)&1027748829^-(t>>4&1)&705979059}function xn(e){let t=1;for(let r=0;r<e.length;++r){let n=e.charCodeAt(r);if(n<33||n>126)return"Invalid prefix ("+e+")";t=Se(t)^n>>5}t=Se(t);for(let r=0;r<e.length;++r){let n=e.charCodeAt(r);t=Se(t)^n&31}return t}function Yt(e,t,r,n){let o=0,s=0,i=(1<<r)-1,a=[];for(let c=0;c<e.length;++c)for(o=o<<t|e[c],s+=t;s>=r;)s-=r,a.push(o>>s&i);if(n)s>0&&a.push(o<<r-s&i);else{if(s>=t)return"Excess padding";if(o<<r-s&i)return"Non-zero padding"}return a}function Yo(e){return Yt(e,8,5,!0)}function Zo(e){let t=Yt(e,5,8,!1);if(Array.isArray(t))return t}function Jo(e){let t=Yt(e,5,8,!1);if(Array.isArray(t))return t;throw new Error(t)}function En(e){let t;e==="bech32"?t=1:t=734539939;function r(i,a,c){if(c=c||90,i.length+7+a.length>c)throw new TypeError("Exceeds length limit");i=i.toLowerCase();let l=xn(i);if(typeof l=="string")throw new Error(l);let u=i+"1";for(let f=0;f<a.length;++f){let b=a[f];if(b>>5!==0)throw new Error("Non 5-bit word");l=Se(l)^b,u+=ft.charAt(b)}for(let f=0;f<6;++f)l=Se(l);l^=t;for(let f=0;f<6;++f){let b=l>>(5-f)*5&31;u+=ft.charAt(b)}return u}function n(i,a){if(a=a||90,i.length<8)return i+" too short";if(i.length>a)return"Exceeds length limit";let c=i.toLowerCase(),l=i.toUpperCase();if(i!==c&&i!==l)return"Mixed-case string "+i;i=c;let u=i.lastIndexOf("1");if(u===-1)return"No separator character for "+i;if(u===0)return"Missing prefix for "+i;let f=i.slice(0,u),b=i.slice(u+1);if(b.length<6)return"Data too short";let x=xn(f);if(typeof x=="string")return x;let A=[];for(let I=0;I<b.length;++I){let L=b.charAt(I),j=wn[L];if(j===void 0)return"Unknown character "+L;x=Se(x)^j,!(I+6>=b.length)&&A.push(j)}return x!==t?"Invalid checksum for "+i:{prefix:f,words:A}}function o(i,a){let c=n(i,a);if(typeof c=="object")return c}function s(i,a){let c=n(i,a);if(typeof c=="object")return c;throw new Error(c)}return{decodeUnsafe:o,decode:s,encode:r,toWords:Yo,fromWordsUnsafe:Zo,fromWords:Jo}}Be.bech32=En("bech32");Be.bech32m=En("bech32m")});var Vn={};uo(Vn,{deleteDB:()=>Ls,openDB:()=>Cs,unwrap:()=>bt,wrap:()=>se});function Ts(){return Cn||(Cn=[IDBDatabase,IDBObjectStore,IDBIndex,IDBCursor,IDBTransaction])}function Is(){return Ln||(Ln=[IDBCursor.prototype.advance,IDBCursor.prototype.continue,IDBCursor.prototype.continuePrimaryKey])}function Rs(e){let t=new Promise((r,n)=>{let o=()=>{e.removeEventListener("success",s),e.removeEventListener("error",i)},s=()=>{r(se(e.result)),o()},i=()=>{n(e.error),o()};e.addEventListener("success",s),e.addEventListener("error",i)});return mt.set(t,e),t}function _s(e){if(nr.has(e))return;let t=new Promise((r,n)=>{let o=()=>{e.removeEventListener("complete",s),e.removeEventListener("error",i),e.removeEventListener("abort",i)},s=()=>{r(),o()},i=()=>{n(e.error||new DOMException("AbortError","AbortError")),o()};e.addEventListener("complete",s),e.addEventListener("error",i),e.addEventListener("abort",i)});nr.set(e,t)}function Pn(e){or=e(or)}function Ds(e){return Is().includes(e)?function(...t){return e.apply(bt(this),t),se(this.request)}:function(...t){return se(e.apply(bt(this),t))}}function Os(e){return typeof e=="function"?Ds(e):(e instanceof IDBTransaction&&_s(e),rr(e,Ts())?new Proxy(e,or):e)}function se(e){if(e instanceof IDBRequest)return Rs(e);if(er.has(e))return er.get(e);let t=Os(e);return t!==e&&(er.set(e,t),mt.set(t,e)),t}function Cs(e,t,{blocked:r,upgrade:n,blocking:o,terminated:s}={}){let i=indexedDB.open(e,t),a=se(i);return n&&i.addEventListener("upgradeneeded",c=>{n(se(i.result),c.oldVersion,c.newVersion,se(i.transaction),c)}),r&&i.addEventListener("blocked",c=>r(c.oldVersion,c.newVersion,c)),a.then(c=>{s&&c.addEventListener("close",()=>s()),o&&c.addEventListener("versionchange",l=>o(l.oldVersion,l.newVersion,l))}).catch(()=>{}),a}function Ls(e,{blocked:t}={}){let r=indexedDB.deleteDatabase(e);return t&&r.addEventListener("blocked",n=>t(n.oldVersion,n)),se(r).then(()=>{})}function Nn(e,t){if(!(e instanceof IDBDatabase&&!(t in e)&&typeof t=="string"))return;if(tr.get(t))return tr.get(t);let r=t.replace(/FromIndex$/,""),n=t!==r,o=Us.includes(r);if(!(r in(n?IDBIndex:IDBObjectStore).prototype)||!(o||Ns.includes(r)))return;let s=async function(i,...a){let c=this.transaction(i,o?"readwrite":"readonly"),l=c.store;return n&&(l=l.index(a.shift())),(await Promise.all([l[r](...a),o&&c.done]))[0]};return tr.set(t,s),s}async function*Fs(...e){let t=this;if(t instanceof IDBCursor||(t=await t.openCursor(...e)),!t)return;t=t;let r=new Proxy(t,Ps);for(Fn.set(r,t),mt.set(r,bt(t));t;)yield r,t=await(sr.get(r)||t.continue()),sr.delete(r)}function Hn(e,t){return t===Symbol.asyncIterator&&rr(e,[IDBIndex,IDBObjectStore,IDBCursor])||t==="iterate"&&rr(e,[IDBIndex,IDBObjectStore])}var rr,Cn,Ln,nr,er,mt,or,bt,Ns,Us,tr,Hs,Un,sr,Fn,Ps,Mn=cr(()=>{d();rr=(e,t)=>t.some(r=>e instanceof r);nr=new WeakMap,er=new WeakMap,mt=new WeakMap;or={get(e,t,r){if(e instanceof IDBTransaction){if(t==="done")return nr.get(e);if(t==="store")return r.objectStoreNames[1]?void 0:r.objectStore(r.objectStoreNames[0])}return se(e[t])},set(e,t,r){return e[t]=r,!0},has(e,t){return e instanceof IDBTransaction&&(t==="done"||t==="store")?!0:t in e}};bt=e=>mt.get(e);Ns=["get","getKey","getAll","getAllKeys","count"],Us=["put","add","delete","clear"],tr=new Map;Pn(e=>({...e,get:(t,r,n)=>Nn(t,r)||e.get(t,r,n),has:(t,r)=>!!Nn(t,r)||e.has(t,r)}));Hs=["continue","continuePrimaryKey","advance"],Un={},sr=new WeakMap,Fn=new WeakMap,Ps={get(e,t){if(!Hs.includes(t))return e[t];let r=Un[t];return r||(r=Un[t]=function(...n){sr.set(this,Fn.get(this)[t](...n))}),r}};Pn(e=>({...e,get(t,r,n){return Hn(t,r)?Fs:e.get(t,r,n)},has(t,r){return Hn(t,r)||e.has(t,r)}}))});d();d();var h=typeof browser<"u"?browser:typeof chrome<"u"?chrome:null;if(!h)throw new Error("browser-polyfill: No extension API namespace found (neither browser nor chrome).");var U=typeof browser>"u"&&typeof chrome<"u";function H(e,t){return(...r)=>{try{let n=t.apply(e,r);if(n&&typeof n.then=="function")return n}catch{}return new Promise((n,o)=>{t.apply(e,[...r,(...s)=>{h.runtime&&h.runtime.lastError?o(new Error(h.runtime.lastError.message)):n(s.length<=1?s[0]:s)}])})}}var z={};z.runtime={sendMessage(...e){return U?H(h.runtime,h.runtime.sendMessage)(...e):h.runtime.sendMessage(...e)},onMessage:h.runtime.onMessage,getURL(e){return h.runtime.getURL(e)},openOptionsPage(){return U?H(h.runtime,h.runtime.openOptionsPage)():h.runtime.openOptionsPage()},get id(){return h.runtime.id}};z.storage={local:{get(...e){return U?H(h.storage.local,h.storage.local.get)(...e):h.storage.local.get(...e)},set(...e){return U?H(h.storage.local,h.storage.local.set)(...e):h.storage.local.set(...e)},clear(...e){return U?H(h.storage.local,h.storage.local.clear)(...e):h.storage.local.clear(...e)},remove(...e){return U?H(h.storage.local,h.storage.local.remove)(...e):h.storage.local.remove(...e)}},sync:h.storage?.sync?{get(...e){return U?H(h.storage.sync,h.storage.sync.get)(...e):h.storage.sync.get(...e)},set(...e){return U?H(h.storage.sync,h.storage.sync.set)(...e):h.storage.sync.set(...e)},remove(...e){return U?H(h.storage.sync,h.storage.sync.remove)(...e):h.storage.sync.remove(...e)},clear(...e){return U?H(h.storage.sync,h.storage.sync.clear)(...e):h.storage.sync.clear(...e)},getBytesInUse(...e){return h.storage.sync.getBytesInUse?U?H(h.storage.sync,h.storage.sync.getBytesInUse)(...e):h.storage.sync.getBytesInUse(...e):Promise.resolve(0)}}:null,onChanged:h.storage?.onChanged||null};z.tabs={create(...e){return U?H(h.tabs,h.tabs.create)(...e):h.tabs.create(...e)},query(...e){return U?H(h.tabs,h.tabs.query)(...e):h.tabs.query(...e)},remove(...e){return U?H(h.tabs,h.tabs.remove)(...e):h.tabs.remove(...e)},update(...e){return U?H(h.tabs,h.tabs.update)(...e):h.tabs.update(...e)},get(...e){return U?H(h.tabs,h.tabs.get)(...e):h.tabs.get(...e)},getCurrent(...e){return U?H(h.tabs,h.tabs.getCurrent)(...e):h.tabs.getCurrent(...e)},sendMessage(...e){return U?H(h.tabs,h.tabs.sendMessage)(...e):h.tabs.sendMessage(...e)}};z.alarms=h.alarms?{create(...e){let t=h.alarms.create(...e);return t&&typeof t.then=="function"?t:Promise.resolve()},clear(...e){return U?H(h.alarms,h.alarms.clear)(...e):h.alarms.clear(...e)},onAlarm:h.alarms.onAlarm}:null;d();d();d();d();d();var ur;(function(e){e[e.SET_METADATA=0]="SET_METADATA",e[e.TEXT_NOTE=1]="TEXT_NOTE",e[e.RECOMMEND_SERVER=2]="RECOMMEND_SERVER",e[e.CONTACTS=3]="CONTACTS",e[e.ENCRYPTED_DIRECT_MESSAGE=4]="ENCRYPTED_DIRECT_MESSAGE",e[e.EVENT_DELETION=5]="EVENT_DELETION",e[e.REPOST=6]="REPOST",e[e.REACTION=7]="REACTION",e[e.CHANNEL_CREATION=40]="CHANNEL_CREATION",e[e.CHANNEL_METADATA=41]="CHANNEL_METADATA",e[e.CHANNEL_MESSAGE=42]="CHANNEL_MESSAGE",e[e.CHANNEL_HIDE_MESSAGE=43]="CHANNEL_HIDE_MESSAGE",e[e.CHANNEL_MUTE_USER=44]="CHANNEL_MUTE_USER",e[e.AUTH=22242]="AUTH",e[e.AUTH_RESPONSE=22243]="AUTH_RESPONSE"})(ur||(ur={}));var Me;(function(e){e.EVENT="EVENT",e.NOTICE="NOTICE",e.OK="OK",e.EOSE="EOSE",e.REQ="REQ",e.CLOSE="CLOSE",e.AUTH="AUTH"})(Me||(Me={}));d();d();d();d();var je;(function(e){e.CONNECT="connect",e.PING="ping",e.GET_PUBLIC_KEY="get_public_key",e.SIGN_EVENT="sign_event",e.NIP04_ENCRYPT="nip04_encrypt",e.NIP04_DECRYPT="nip04_decrypt",e.NIP44_ENCRYPT="nip44_encrypt",e.NIP44_DECRYPT="nip44_decrypt",e.GET_RELAYS="get_relays"})(je||(je={}));var St;(function(e){e[e.SET_METADATA=0]="SET_METADATA",e[e.TEXT_NOTE=1]="TEXT_NOTE",e[e.RECOMMEND_SERVER=2]="RECOMMEND_SERVER",e[e.CONTACT_LIST=3]="CONTACT_LIST",e[e.ENCRYPTED_DIRECT_MESSAGE=4]="ENCRYPTED_DIRECT_MESSAGE",e[e.DELETE=5]="DELETE",e[e.REPOST=6]="REPOST",e[e.REACTION=7]="REACTION",e[e.BADGE_AWARD=8]="BADGE_AWARD",e[e.CHANNEL_CREATE=40]="CHANNEL_CREATE",e[e.CHANNEL_METADATA=41]="CHANNEL_METADATA",e[e.CHANNEL_MESSAGE=42]="CHANNEL_MESSAGE",e[e.CHANNEL_HIDE_MESSAGE=43]="CHANNEL_HIDE_MESSAGE",e[e.CHANNEL_MUTE_USER=44]="CHANNEL_MUTE_USER",e[e.CHANNEL_RESERVE=45]="CHANNEL_RESERVE",e[e.REPORTING=1984]="REPORTING",e[e.ZAP_REQUEST=9734]="ZAP_REQUEST",e[e.ZAP=9735]="ZAP",e[e.MUTE_LIST=1e4]="MUTE_LIST",e[e.PIN_LIST=10001]="PIN_LIST",e[e.RELAY_LIST_METADATA=10002]="RELAY_LIST_METADATA",e[e.CLIENT_AUTH=22242]="CLIENT_AUTH",e[e.AUTH_RESPONSE=22243]="AUTH_RESPONSE",e[e.NOSTR_CONNECT=24133]="NOSTR_CONNECT",e[e.CATEGORIZED_PEOPLE=3e4]="CATEGORIZED_PEOPLE",e[e.CATEGORIZED_BOOKMARKS=30001]="CATEGORIZED_BOOKMARKS",e[e.PROFILE_BADGES=30008]="PROFILE_BADGES",e[e.BADGE_DEFINITION=30009]="BADGE_DEFINITION",e[e.LONG_FORM=30023]="LONG_FORM",e[e.APPLICATION_SPECIFIC=30078]="APPLICATION_SPECIFIC"})(St||(St={}));d();d();d();d();d();function pr(e){return e instanceof Uint8Array||ArrayBuffer.isView(e)&&e.constructor.name==="Uint8Array"&&"BYTES_PER_ELEMENT"in e&&e.BYTES_PER_ELEMENT===1}function qe(e,t=""){if(typeof e!="number"){let r=t&&`"${t}" `;throw new TypeError(`${r}expected number, got ${typeof e}`)}if(!Number.isSafeInteger(e)||e<0){let r=t&&`"${t}" `;throw new RangeError(`${r}expected integer >= 0, got ${e}`)}}function ie(e,t,r=""){let n=pr(e),o=e?.length,s=t!==void 0;if(!n||s&&o!==t){let i=r&&`"${r}" `,a=s?` of length ${t}`:"",c=n?`length=${o}`:`type=${typeof e}`,l=i+"expected Uint8Array"+a+", got "+c;throw n?new RangeError(l):new TypeError(l)}return e}function Bt(e,t=!0){if(e.destroyed)throw new Error("Hash instance has been destroyed");if(t&&e.finished)throw new Error("Hash#digest() has already been called")}function hr(e,t){ie(e,void 0,"digestInto() output");let r=t.outputLen;if(e.length<r)throw new RangeError('"digestInto() output" expected to be of length >='+r)}function De(...e){for(let t=0;t<e.length;t++)e[t].fill(0)}function ze(e){return new DataView(e.buffer,e.byteOffset,e.byteLength)}function Y(e,t){return e<<32-t|e>>>t}var yr=typeof Uint8Array.from([]).toHex=="function"&&typeof Uint8Array.fromHex=="function",ho=Array.from({length:256},(e,t)=>t.toString(16).padStart(2,"0"));function $e(e){if(ie(e),yr)return e.toHex();let t="";for(let r=0;r<e.length;r++)t+=ho[e[r]];return t}var ee={_0:48,_9:57,A:65,F:70,a:97,f:102};function dr(e){if(e>=ee._0&&e<=ee._9)return e-ee._0;if(e>=ee.A&&e<=ee.F)return e-(ee.A-10);if(e>=ee.a&&e<=ee.f)return e-(ee.a-10)}function kt(e){if(typeof e!="string")throw new TypeError("hex string expected, got "+typeof e);if(yr)try{return Uint8Array.fromHex(e)}catch(o){throw o instanceof SyntaxError?new RangeError(o.message):o}let t=e.length,r=t/2;if(t%2)throw new RangeError("hex string expected, got unpadded hex of length "+t);let n=new Uint8Array(r);for(let o=0,s=0;o<r;o++,s+=2){let i=dr(e.charCodeAt(s)),a=dr(e.charCodeAt(s+1));if(i===void 0||a===void 0){let c=e[s]+e[s+1];throw new RangeError('hex string expected, got non-hex character "'+c+'" at index '+s)}n[o]=i*16+a}return n}function br(...e){let t=0;for(let n=0;n<e.length;n++){let o=e[n];ie(o),t+=o.length}let r=new Uint8Array(t);for(let n=0,o=0;n<e.length;n++){let s=e[n];r.set(s,o),o+=s.length}return r}function mr(e,t={}){let r=(o,s)=>e(s).update(o).digest(),n=e(void 0);return r.outputLen=n.outputLen,r.blockLen=n.blockLen,r.canXOF=n.canXOF,r.create=o=>e(o),Object.assign(r,t),Object.freeze(r)}function Ge(e=32){qe(e,"bytesLength");let t=typeof globalThis=="object"?globalThis.crypto:null;if(typeof t?.getRandomValues!="function")throw new Error("crypto.getRandomValues must be defined");if(e>65536)throw new RangeError(`"bytesLength" expected <= 65536, got ${e}`);return t.getRandomValues(new Uint8Array(e))}var gr=e=>({oid:Uint8Array.from([6,9,96,134,72,1,101,3,4,2,e])});function xr(e,t,r){return e&t^~e&r}function wr(e,t,r){return e&t^e&r^t&r}var Ke=class{blockLen;outputLen;canXOF=!1;padOffset;isLE;buffer;view;finished=!1;length=0;pos=0;destroyed=!1;constructor(t,r,n,o){this.blockLen=t,this.outputLen=r,this.padOffset=n,this.isLE=o,this.buffer=new Uint8Array(t),this.view=ze(this.buffer)}update(t){Bt(this),ie(t);let{view:r,buffer:n,blockLen:o}=this,s=t.length;for(let i=0;i<s;){let a=Math.min(o-this.pos,s-i);if(a===o){let c=ze(t);for(;o<=s-i;i+=o)this.process(c,i);continue}n.set(t.subarray(i,i+a),this.pos),this.pos+=a,i+=a,this.pos===o&&(this.process(r,0),this.pos=0)}return this.length+=t.length,this.roundClean(),this}digestInto(t){Bt(this),hr(t,this),this.finished=!0;let{buffer:r,view:n,blockLen:o,isLE:s}=this,{pos:i}=this;r[i++]=128,De(this.buffer.subarray(i)),this.padOffset>o-i&&(this.process(n,0),i=0);for(let f=i;f<o;f++)r[f]=0;n.setBigUint64(o-8,BigInt(this.length*8),s),this.process(n,0);let a=ze(t),c=this.outputLen;if(c%4)throw new Error("_sha2: outputLen must be aligned to 32bit");let l=c/4,u=this.get();if(l>u.length)throw new Error("_sha2: outputLen bigger than state");for(let f=0;f<l;f++)a.setUint32(4*f,u[f],s)}digest(){let{buffer:t,outputLen:r}=this;this.digestInto(t);let n=t.slice(0,r);return this.destroy(),n}_cloneInto(t){t||=new this.constructor,t.set(...this.get());let{blockLen:r,buffer:n,length:o,finished:s,destroyed:i,pos:a}=this;return t.destroyed=i,t.finished=s,t.length=o,t.pos=a,o%r&&t.buffer.set(n),t}clone(){return this._cloneInto()}},te=Uint32Array.from([1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225]);var yo=Uint32Array.from([1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298]),ae=new Uint32Array(64),Tt=class extends Ke{constructor(t){super(64,t,8,!1)}get(){let{A:t,B:r,C:n,D:o,E:s,F:i,G:a,H:c}=this;return[t,r,n,o,s,i,a,c]}set(t,r,n,o,s,i,a,c){this.A=t|0,this.B=r|0,this.C=n|0,this.D=o|0,this.E=s|0,this.F=i|0,this.G=a|0,this.H=c|0}process(t,r){for(let f=0;f<16;f++,r+=4)ae[f]=t.getUint32(r,!1);for(let f=16;f<64;f++){let b=ae[f-15],x=ae[f-2],A=Y(b,7)^Y(b,18)^b>>>3,I=Y(x,17)^Y(x,19)^x>>>10;ae[f]=I+ae[f-7]+A+ae[f-16]|0}let{A:n,B:o,C:s,D:i,E:a,F:c,G:l,H:u}=this;for(let f=0;f<64;f++){let b=Y(a,6)^Y(a,11)^Y(a,25),x=u+b+xr(a,c,l)+yo[f]+ae[f]|0,I=(Y(n,2)^Y(n,13)^Y(n,22))+wr(n,o,s)|0;u=l,l=c,c=a,a=i+x|0,i=s,s=o,o=n,n=x+I|0}n=n+this.A|0,o=o+this.B|0,s=s+this.C|0,i=i+this.D|0,a=a+this.E|0,c=c+this.F|0,l=l+this.G|0,u=u+this.H|0,this.set(n,o,s,i,a,c,l,u)}roundClean(){De(ae)}destroy(){this.destroyed=!0,this.set(0,0,0,0,0,0,0,0),De(this.buffer)}},It=class extends Tt{A=te[0]|0;B=te[1]|0;C=te[2]|0;D=te[3]|0;E=te[4]|0;F=te[5]|0;G=te[6]|0;H=te[7]|0;constructor(){super(32)}};var Rt=mr(()=>new It,gr(1));d();d();var M=(e,t,r)=>ie(e,t,r),Dt=qe,Er=$e,me=(...e)=>br(...e),vr=e=>kt(e);var Ye=BigInt(0),_t=BigInt(1);function Oe(e,t=""){if(typeof e!="boolean"){let r=t&&`"${t}" `;throw new TypeError(r+"expected boolean, got type="+typeof e)}return e}function Ze(e){if(typeof e=="bigint"){if(!We(e))throw new RangeError("positive bigint expected, got "+e)}else Dt(e);return e}function Ce(e,t=""){if(typeof e!="number"){let r=t&&`"${t}" `;throw new TypeError(r+"expected number, got type="+typeof e)}if(!Number.isSafeInteger(e)){let r=t&&`"${t}" `;throw new RangeError(r+"expected safe integer, got "+e)}}function Le(e){let t=Ze(e).toString(16);return t.length&1?"0"+t:t}function Ar(e){if(typeof e!="string")throw new TypeError("hex string expected, got "+typeof e);return e===""?Ye:BigInt("0x"+e)}function fe(e){return Ar($e(e))}function Ot(e){return Ar($e(bo(ie(e)).reverse()))}function Je(e,t){if(qe(t),t===0)throw new RangeError("zero length");e=Ze(e);let r=e.toString(16);if(r.length>t*2)throw new RangeError("number too large");return kt(r.padStart(t*2,"0"))}function Ct(e,t){return Je(e,t).reverse()}function bo(e){return Uint8Array.from(M(e))}function Sr(e){if(typeof e!="string")throw new TypeError("ascii string expected, got "+typeof e);return Uint8Array.from(e,(t,r)=>{let n=t.charCodeAt(0);if(t.length!==1||n>127)throw new RangeError(`string contains non-ASCII character "${e[r]}" with code ${n} at position ${r}`);return n})}var We=e=>typeof e=="bigint"&&Ye<=e;function mo(e,t,r){return We(e)&&We(t)&&We(r)&&t<=e&&e<r}function Br(e,t,r,n){if(!mo(t,r,n))throw new RangeError("expected valid "+e+": "+r+" <= n < "+n+", got "+t)}function ge(e){if(e<Ye)throw new Error("expected non-negative bigint, got "+e);let t;for(t=0;e>Ye;e>>=_t,t+=1);return t}var Xe=e=>(_t<<BigInt(e))-_t;function Ne(e,t={},r={}){if(Object.prototype.toString.call(e)!=="[object Object]")throw new TypeError("expected valid options object");function n(s,i,a){if(!a&&i!=="function"&&!Object.hasOwn(e,s))throw new TypeError(`param "${s}" is invalid: expected own property`);let c=e[s];if(a&&c===void 0)return;let l=typeof c;if(l!==i||c===null)throw new TypeError(`param "${s}" is invalid: expected ${i}, got ${l}`)}let o=(s,i)=>Object.entries(s).forEach(([a,c])=>n(a,c,i));o(t,!1),o(r,!0)}d();var F=BigInt(0),C=BigInt(1),ue=BigInt(2),Rr=BigInt(3),_r=BigInt(4),Dr=BigInt(5),go=BigInt(7),Or=BigInt(8),xo=BigInt(9),Cr=BigInt(16);function Z(e,t){if(t<=F)throw new Error("mod: expected positive modulus, got "+t);let r=e%t;return r>=F?r:t+r}function $(e,t,r){if(t<F)throw new Error("pow2: expected non-negative exponent, got "+t);let n=e;for(;t-- >F;)n*=n,n%=r;return n}function kr(e,t){if(e===F)throw new Error("invert: expected non-zero number");if(t<=F)throw new Error("invert: expected positive modulus, got "+t);let r=Z(e,t),n=t,o=F,s=C,i=C,a=F;for(;r!==F;){let l=n/r,u=n-r*l,f=o-i*l,b=s-a*l;n=r,r=u,o=i,s=a,i=f,a=b}if(n!==C)throw new Error("invert: does not exist");return Z(o,t)}function Lt(e,t,r){let n=e;if(!n.eql(n.sqr(t),r))throw new Error("Cannot find square root")}function Lr(e,t){let r=e,n=(r.ORDER+C)/_r,o=r.pow(t,n);return Lt(r,o,t),o}function wo(e,t){let r=e,n=(r.ORDER-Dr)/Or,o=r.mul(t,ue),s=r.pow(o,n),i=r.mul(t,s),a=r.mul(r.mul(i,ue),s),c=r.mul(i,r.sub(a,r.ONE));return Lt(r,c,t),c}function Eo(e){let t=xe(e),r=Nr(e),n=r(t,t.neg(t.ONE)),o=r(t,n),s=r(t,t.neg(n)),i=(e+go)/Cr;return((a,c)=>{let l=a,u=l.pow(c,i),f=l.mul(u,n),b=l.mul(u,o),x=l.mul(u,s),A=l.eql(l.sqr(f),c),I=l.eql(l.sqr(b),c);u=l.cmov(u,f,A),f=l.cmov(x,b,I);let L=l.eql(l.sqr(f),c),j=l.cmov(u,f,L);return Lt(l,j,c),j})}function Nr(e){if(e<Rr)throw new Error("sqrt is not defined for small field");let t=e-C,r=0;for(;t%ue===F;)t/=ue,r++;let n=ue,o=xe(e);for(;Tr(o,n)===1;)if(n++>1e3)throw new Error("Cannot find square root: probably non-prime P");if(r===1)return Lr;let s=o.pow(n,t),i=(t+C)/ue;return function(c,l){let u=c;if(u.is0(l))return l;if(Tr(u,l)!==1)throw new Error("Cannot find square root");let f=r,b=u.mul(u.ONE,s),x=u.pow(l,t),A=u.pow(l,i);for(;!u.eql(x,u.ONE);){if(u.is0(x))return u.ZERO;let I=1,L=u.sqr(x);for(;!u.eql(L,u.ONE);)if(I++,L=u.sqr(L),I===f)throw new Error("Cannot find square root");let j=C<<BigInt(f-I-1),ye=u.pow(b,j);f=I,b=u.sqr(ye),x=u.mul(x,b),A=u.mul(A,ye)}return A}}function vo(e){return e%_r===Rr?Lr:e%Or===Dr?wo:e%Cr===xo?Eo(e):Nr(e)}var Ao=["create","isValid","is0","neg","inv","sqrt","sqr","eql","add","sub","mul","pow","div","addN","subN","mulN","sqrN"];function Ur(e){let t={ORDER:"bigint",BYTES:"number",BITS:"number"},r=Ao.reduce((n,o)=>(n[o]="function",n),t);if(Ne(e,r),Ce(e.BYTES,"BYTES"),Ce(e.BITS,"BITS"),e.BYTES<1||e.BITS<1)throw new Error("invalid field: expected BYTES/BITS > 0");if(e.ORDER<=C)throw new Error("invalid field: expected ORDER > 1, got "+e.ORDER);return e}function So(e,t,r){let n=e;if(r<F)throw new Error("invalid exponent, negatives unsupported");if(r===F)return n.ONE;if(r===C)return t;let o=n.ONE,s=t;for(;r>F;)r&C&&(o=n.mul(o,s)),s=n.sqr(s),r>>=C;return o}function Nt(e,t,r=!1){let n=e,o=new Array(t.length).fill(r?n.ZERO:void 0),s=t.reduce((a,c,l)=>n.is0(c)?a:(o[l]=a,n.mul(a,c)),n.ONE),i=n.inv(s);return t.reduceRight((a,c,l)=>n.is0(c)?a:(o[l]=n.mul(a,o[l]),n.mul(a,c)),i),o}function Tr(e,t){let r=e,n=(r.ORDER-C)/ue,o=r.pow(t,n),s=r.eql(o,r.ONE),i=r.eql(o,r.ZERO),a=r.eql(o,r.neg(r.ONE));if(!s&&!i&&!a)throw new Error("invalid Legendre symbol result");return s?1:i?0:-1}function Bo(e,t){if(t!==void 0&&Dt(t),e<=F)throw new Error("invalid n length: expected positive n, got "+e);if(t!==void 0&&t<1)throw new Error("invalid n length: expected positive bit length, got "+t);let r=ge(e);if(t!==void 0&&t<r)throw new Error(`invalid n length: expected bit length (${r}) >= n.length (${t})`);let n=t!==void 0?t:r,o=Math.ceil(n/8);return{nBitLength:n,nByteLength:o}}var Ir=new WeakMap,Qe=class{ORDER;BITS;BYTES;isLE;ZERO=F;ONE=C;_lengths;_mod;constructor(t,r={}){if(t<=C)throw new Error("invalid field: expected ORDER > 1, got "+t);let n;this.isLE=!1,r!=null&&typeof r=="object"&&(typeof r.BITS=="number"&&(n=r.BITS),typeof r.sqrt=="function"&&Object.defineProperty(this,"sqrt",{value:r.sqrt,enumerable:!0}),typeof r.isLE=="boolean"&&(this.isLE=r.isLE),r.allowedLengths&&(this._lengths=Object.freeze(r.allowedLengths.slice())),typeof r.modFromBytes=="boolean"&&(this._mod=r.modFromBytes));let{nBitLength:o,nByteLength:s}=Bo(t,n);if(s>2048)throw new Error("invalid field: expected ORDER of <= 2048 bytes");this.ORDER=t,this.BITS=o,this.BYTES=s,Object.freeze(this)}create(t){return Z(t,this.ORDER)}isValid(t){if(typeof t!="bigint")throw new TypeError("invalid field element: expected bigint, got "+typeof t);return F<=t&&t<this.ORDER}is0(t){return t===F}isValidNot0(t){return!this.is0(t)&&this.isValid(t)}isOdd(t){return(t&C)===C}neg(t){return Z(-t,this.ORDER)}eql(t,r){return t===r}sqr(t){return Z(t*t,this.ORDER)}add(t,r){return Z(t+r,this.ORDER)}sub(t,r){return Z(t-r,this.ORDER)}mul(t,r){return Z(t*r,this.ORDER)}pow(t,r){return So(this,t,r)}div(t,r){return Z(t*kr(r,this.ORDER),this.ORDER)}sqrN(t){return t*t}addN(t,r){return t+r}subN(t,r){return t-r}mulN(t,r){return t*r}inv(t){return kr(t,this.ORDER)}sqrt(t){let r=Ir.get(this);return r||Ir.set(this,r=vo(this.ORDER)),r(this,t)}toBytes(t){return this.isLE?Ct(t,this.BYTES):Je(t,this.BYTES)}fromBytes(t,r=!1){M(t);let{_lengths:n,BYTES:o,isLE:s,ORDER:i,_mod:a}=this;if(n){if(t.length<1||!n.includes(t.length)||t.length>o)throw new Error("Field.fromBytes: expected "+n+" bytes, got "+t.length);let l=new Uint8Array(o);l.set(t,s?0:l.length-t.length),t=l}if(t.length!==o)throw new Error("Field.fromBytes: expected "+o+" bytes, got "+t.length);let c=s?Ot(t):fe(t);if(a&&(c=Z(c,i)),!r&&!this.isValid(c))throw new Error("invalid field element: outside of range 0..ORDER");return c}invertBatch(t){return Nt(this,t)}cmov(t,r,n){return Oe(n,"condition"),n?r:t}};Object.freeze(Qe.prototype);function xe(e,t={}){return new Qe(e,t)}function Hr(e){if(typeof e!="bigint")throw new Error("field order must be bigint");if(e<=C)throw new Error("field order must be greater than 1");let t=ge(e-C);return Math.ceil(t/8)}function ko(e){let t=Hr(e);return t+Math.ceil(t/2)}function Pr(e,t,r=!1){M(e);let n=e.length,o=Hr(t),s=Math.max(ko(t),16);if(n<s||n>1024)throw new Error("expected "+s+"-1024 bytes of input, got "+n);let i=r?Ot(e):fe(e),a=Z(i,t-C)+C;return r?Ct(a,o):Je(a,o)}var we=BigInt(0),de=BigInt(1);function Ue(e,t){let r=t.negate();return e?r:t}function Ft(e,t){let r=Nt(e.Fp,t.map(n=>n.Z));return t.map((n,o)=>e.fromAffine(n.toAffine(r[o])))}function jr(e,t){if(!Number.isSafeInteger(e)||e<=0||e>t)throw new Error("invalid window size, expected [1.."+t+"], got W="+e)}function Ut(e,t){jr(e,t);let r=Math.ceil(t/e)+1,n=2**(e-1),o=2**e,s=Xe(e),i=BigInt(e);return{windows:r,windowSize:n,mask:s,maxNumber:o,shiftBy:i}}function Fr(e,t,r){let{windowSize:n,mask:o,maxNumber:s,shiftBy:i}=r,a=Number(e&o),c=e>>i;a>n&&(a-=s,c+=de);let l=t*n,u=l+Math.abs(a)-1,f=a===0,b=a<0,x=t%2!==0;return{nextN:c,offset:u,isZero:f,isNeg:b,isNegF:x,offsetF:l}}var Ht=new WeakMap,qr=new WeakMap;function Pt(e){return qr.get(e)||1}function Vr(e){if(e!==we)throw new Error("invalid wNAF")}var et=class{BASE;ZERO;Fn;bits;constructor(t,r){this.BASE=t.BASE,this.ZERO=t.ZERO,this.Fn=t.Fn,this.bits=r}_unsafeLadder(t,r,n=this.ZERO){let o=t;for(;r>we;)r&de&&(n=n.add(o)),o=o.double(),r>>=de;return n}precomputeWindow(t,r){let{windows:n,windowSize:o}=Ut(r,this.bits),s=[],i=t,a=i;for(let c=0;c<n;c++){a=i,s.push(a);for(let l=1;l<o;l++)a=a.add(i),s.push(a);i=a.double()}return s}wNAF(t,r,n){if(!this.Fn.isValid(n))throw new Error("invalid scalar");let o=this.ZERO,s=this.BASE,i=Ut(t,this.bits);for(let a=0;a<i.windows;a++){let{nextN:c,offset:l,isZero:u,isNeg:f,isNegF:b,offsetF:x}=Fr(n,a,i);n=c,u?s=s.add(Ue(b,r[x])):o=o.add(Ue(f,r[l]))}return Vr(n),{p:o,f:s}}wNAFUnsafe(t,r,n,o=this.ZERO){let s=Ut(t,this.bits);for(let i=0;i<s.windows&&n!==we;i++){let{nextN:a,offset:c,isZero:l,isNeg:u}=Fr(n,i,s);if(n=a,!l){let f=r[c];o=o.add(u?f.negate():f)}}return Vr(n),o}getPrecomputes(t,r,n){let o=Ht.get(r);return o||(o=this.precomputeWindow(r,t),t!==1&&(typeof n=="function"&&(o=n(o)),Ht.set(r,o))),o}cached(t,r,n){let o=Pt(t);return this.wNAF(o,this.getPrecomputes(o,t,n),r)}unsafe(t,r,n,o){let s=Pt(t);return s===1?this._unsafeLadder(t,r,o):this.wNAFUnsafe(s,this.getPrecomputes(s,t,n),r,o)}createCache(t,r){jr(r,this.bits),qr.set(t,r),Ht.delete(t)}hasCache(t){return Pt(t)!==1}};function zr(e,t,r,n){let o=t,s=e.ZERO,i=e.ZERO;for(;r>we||n>we;)r&de&&(s=s.add(o)),n&de&&(i=i.add(o)),o=o.double(),r>>=de,n>>=de;return{p1:s,p2:i}}function Mr(e,t,r){if(t){if(t.ORDER!==e)throw new Error("Field.ORDER must match order: Fp == p, Fn == n");return Ur(t),t}else return xe(e,{isLE:r})}function $r(e,t,r={},n){if(n===void 0&&(n=e==="edwards"),!t||typeof t!="object")throw new Error(`expected valid ${e} CURVE object`);for(let c of["p","n","h"]){let l=t[c];if(!(typeof l=="bigint"&&l>we))throw new Error(`CURVE.${c} must be positive bigint`)}let o=Mr(t.p,r.Fp,n),s=Mr(t.n,r.Fn,n),a=["Gx","Gy","a",e==="weierstrass"?"b":"d"];for(let c of a)if(!o.isValid(t[c]))throw new Error(`CURVE.${c} must be valid field element of CURVE.Fp`);return t=Object.freeze(Object.assign({},t)),{CURVE:t,Fp:o,Fn:s}}function Vt(e,t){return function(n){let o=e(n);return{secretKey:o,publicKey:t(o)}}}d();var Gr=(e,t)=>(e+(e>=0?t:-t)/Io)/t;function To(e,t,r){Br("scalar",e,pe,r);let[[n,o],[s,i]]=t,a=Gr(i*e,r),c=Gr(-o*e,r),l=e-a*n-c*s,u=-a*o-c*i,f=l<pe,b=u<pe;f&&(l=-l),b&&(u=-u);let x=Xe(Math.ceil(ge(r)/2))+He;if(l<pe||l>=x||u<pe||u>=x)throw new Error("splitScalar (endomorphism): failed for k");return{k1neg:f,k1:l,k2neg:b,k2:u}}var Mt=class extends Error{constructor(t=""){super(t)}},re={Err:Mt,_tlv:{encode:(e,t)=>{let{Err:r}=re;if(Ce(e,"tag"),e<0||e>255)throw new r("tlv.encode: wrong tag");if(typeof t!="string")throw new TypeError('"data" expected string, got type='+typeof t);if(t.length&1)throw new r("tlv.encode: unpadded data");let n=t.length/2,o=Le(n);if(o.length/2&128)throw new r("tlv.encode: long form length too big");let s=n>127?Le(o.length/2|128):"";return Le(e)+s+o+t},decode(e,t){let{Err:r}=re;t=M(t,void 0,"DER data");let n=0;if(e<0||e>255)throw new r("tlv.encode: wrong tag");if(t.length<2||t[n++]!==e)throw new r("tlv.decode: wrong tlv");let o=t[n++],s=!!(o&128),i=0;if(!s)i=o;else{let c=o&127;if(!c)throw new r("tlv.decode(long): indefinite length not supported");if(c>4)throw new r("tlv.decode(long): byte length is too big");let l=t.subarray(n,n+c);if(l.length!==c)throw new r("tlv.decode: length bytes not complete");if(l[0]===0)throw new r("tlv.decode(long): zero leftmost byte");for(let u of l)i=i<<8|u;if(n+=c,i<128)throw new r("tlv.decode(long): not minimal encoding")}let a=t.subarray(n,n+i);if(a.length!==i)throw new r("tlv.decode: wrong value length");return{v:a,l:t.subarray(n+i)}}},_int:{encode(e){let{Err:t}=re;if(Ze(e),e<pe)throw new t("integer: negative integers are not allowed");let r=Le(e);if(Number.parseInt(r[0],16)&8&&(r="00"+r),r.length&1)throw new t("unexpected DER parsing assertion: unpadded hex");return r},decode(e){let{Err:t}=re;if(e.length<1)throw new t("invalid signature integer: empty");if(e[0]&128)throw new t("invalid signature integer: negative");if(e.length>1&&e[0]===0&&!(e[1]&128))throw new t("invalid signature integer: unnecessary leading zero");return fe(e)}},toSig(e){let{Err:t,_int:r,_tlv:n}=re,o=M(e,void 0,"signature"),{v:s,l:i}=n.decode(48,o);if(i.length)throw new t("invalid signature: left bytes after parsing");let{v:a,l:c}=n.decode(2,s),{v:l,l:u}=n.decode(2,c);if(u.length)throw new t("invalid signature: left bytes after parsing");return{r:r.decode(a),s:r.decode(l)}},hexFromSig(e){let{_tlv:t,_int:r}=re,n=t.encode(2,r.encode(e.r)),o=t.encode(2,r.encode(e.s)),s=n+o;return t.encode(48,s)}};Object.freeze(re._tlv);Object.freeze(re._int);Object.freeze(re);var pe=BigInt(0),He=BigInt(1),Io=BigInt(2),tt=BigInt(3),Ro=BigInt(4);function Kr(e,t={}){let r=$r("weierstrass",e,t),n=r.Fp,o=r.Fn,s=r.CURVE,{h:i,n:a}=s;Ne(t,{},{allowInfinityPoint:"boolean",clearCofactor:"function",isTorsionFree:"function",fromBytes:"function",toBytes:"function",endo:"object"});let{endo:c,allowInfinityPoint:l}=t;if(c&&(!n.is0(s.a)||typeof c.beta!="bigint"||!Array.isArray(c.basises)))throw new Error('invalid endo: expected "beta": bigint and "basises": array');let u=Do(n,o);function f(){if(!n.isOdd)throw new Error("compression is not supported: Field does not have .isOdd()")}function b(N,p,g){if(l&&p.is0())return Uint8Array.of(0);let{x:w,y:v}=p.toAffine(),D=n.toBytes(w);if(Oe(g,"isCompressed"),g){f();let B=!n.isOdd(v);return me(_o(B),D)}else return me(Uint8Array.of(4),D,n.toBytes(v))}function x(N){M(N,void 0,"Point");let{publicKey:p,publicKeyUncompressed:g}=u,w=N.length,v=N[0],D=N.subarray(1);if(l&&w===1&&v===0)return{x:n.ZERO,y:n.ZERO};if(w===p&&(v===2||v===3)){let B=n.fromBytes(D);if(!n.isValid(B))throw new Error("bad point: is not on curve, wrong x");let k=L(B),E;try{E=n.sqrt(k)}catch(G){let P=G instanceof Error?": "+G.message:"";throw new Error("bad point: is not on curve, sqrt error"+P)}f();let S=n.isOdd(E);return(v&1)===1!==S&&(E=n.neg(E)),{x:B,y:E}}else if(w===g&&v===4){let B=n.BYTES,k=n.fromBytes(D.subarray(0,B)),E=n.fromBytes(D.subarray(B,B*2));if(!j(k,E))throw new Error("bad point: is not on curve");return{x:k,y:E}}else throw new Error(`bad point: got length ${w}, expected compressed=${p} or uncompressed=${g}`)}let A=t.toBytes===void 0?b:t.toBytes,I=t.fromBytes===void 0?x:t.fromBytes;function L(N){let p=n.sqr(N),g=n.mul(p,N);return n.add(n.add(g,n.mul(N,s.a)),s.b)}function j(N,p){let g=n.sqr(p),w=L(N);return n.eql(g,w)}if(!j(s.Gx,s.Gy))throw new Error("bad curve params: generator point");let ye=n.mul(n.pow(s.a,tt),Ro),Et=n.mul(n.sqr(s.b),BigInt(27));if(n.is0(n.add(ye,Et)))throw new Error("bad curve params: a or b");function Te(N,p,g=!1){if(!n.isValid(p)||g&&n.is0(p))throw new Error(`bad point coordinate ${N}`);return p}function Ie(N){if(!(N instanceof _))throw new Error("Weierstrass Point expected")}function Re(N){if(!c||!c.basises)throw new Error("no endo");return To(N,c.basises,o.ORDER)}function ar(N,p,g,w,v){return g=new _(n.mul(g.X,N),g.Y,g.Z),p=Ue(w,p),g=Ue(v,g),p.add(g)}class _{static BASE=new _(s.Gx,s.Gy,n.ONE);static ZERO=new _(n.ZERO,n.ONE,n.ZERO);static Fp=n;static Fn=o;X;Y;Z;constructor(p,g,w){this.X=Te("x",p),this.Y=Te("y",g,!0),this.Z=Te("z",w),Object.freeze(this)}static CURVE(){return s}static fromAffine(p){let{x:g,y:w}=p||{};if(!p||!n.isValid(g)||!n.isValid(w))throw new Error("invalid affine point");if(p instanceof _)throw new Error("projective point not allowed");return n.is0(g)&&n.is0(w)?_.ZERO:new _(g,w,n.ONE)}static fromBytes(p){let g=_.fromAffine(I(M(p,void 0,"point")));return g.assertValidity(),g}static fromHex(p){return _.fromBytes(vr(p))}get x(){return this.toAffine().x}get y(){return this.toAffine().y}precompute(p=8,g=!0){return _e.createCache(this,p),g||this.multiply(tt),this}assertValidity(){let p=this;if(p.is0()){if(t.allowInfinityPoint&&n.is0(p.X)&&n.eql(p.Y,n.ONE)&&n.is0(p.Z))return;throw new Error("bad point: ZERO")}let{x:g,y:w}=p.toAffine();if(!n.isValid(g)||!n.isValid(w))throw new Error("bad point: x or y not field elements");if(!j(g,w))throw new Error("bad point: equation left != right");if(!p.isTorsionFree())throw new Error("bad point: not in prime-order subgroup")}hasEvenY(){let{y:p}=this.toAffine();if(!n.isOdd)throw new Error("Field doesn't support isOdd");return!n.isOdd(p)}equals(p){Ie(p);let{X:g,Y:w,Z:v}=this,{X:D,Y:B,Z:k}=p,E=n.eql(n.mul(g,k),n.mul(D,v)),S=n.eql(n.mul(w,k),n.mul(B,v));return E&&S}negate(){return new _(this.X,n.neg(this.Y),this.Z)}double(){let{a:p,b:g}=s,w=n.mul(g,tt),{X:v,Y:D,Z:B}=this,k=n.ZERO,E=n.ZERO,S=n.ZERO,T=n.mul(v,v),G=n.mul(D,D),P=n.mul(B,B),O=n.mul(v,D);return O=n.add(O,O),S=n.mul(v,B),S=n.add(S,S),k=n.mul(p,S),E=n.mul(w,P),E=n.add(k,E),k=n.sub(G,E),E=n.add(G,E),E=n.mul(k,E),k=n.mul(O,k),S=n.mul(w,S),P=n.mul(p,P),O=n.sub(T,P),O=n.mul(p,O),O=n.add(O,S),S=n.add(T,T),T=n.add(S,T),T=n.add(T,P),T=n.mul(T,O),E=n.add(E,T),P=n.mul(D,B),P=n.add(P,P),T=n.mul(P,O),k=n.sub(k,T),S=n.mul(P,G),S=n.add(S,S),S=n.add(S,S),new _(k,E,S)}add(p){Ie(p);let{X:g,Y:w,Z:v}=this,{X:D,Y:B,Z:k}=p,E=n.ZERO,S=n.ZERO,T=n.ZERO,G=s.a,P=n.mul(s.b,tt),O=n.mul(g,D),K=n.mul(w,B),W=n.mul(v,k),be=n.add(g,w),V=n.add(D,B);be=n.mul(be,V),V=n.add(O,K),be=n.sub(be,V),V=n.add(g,v);let Q=n.add(D,k);return V=n.mul(V,Q),Q=n.add(O,W),V=n.sub(V,Q),Q=n.add(w,v),E=n.add(B,k),Q=n.mul(Q,E),E=n.add(K,W),Q=n.sub(Q,E),T=n.mul(G,V),E=n.mul(P,W),T=n.add(E,T),E=n.sub(K,T),T=n.add(K,T),S=n.mul(E,T),K=n.add(O,O),K=n.add(K,O),W=n.mul(G,W),V=n.mul(P,V),K=n.add(K,W),W=n.sub(O,W),W=n.mul(G,W),V=n.add(V,W),O=n.mul(K,V),S=n.add(S,O),O=n.mul(Q,V),E=n.mul(be,E),E=n.sub(E,O),O=n.mul(be,K),T=n.mul(Q,T),T=n.add(T,O),new _(E,S,T)}subtract(p){return Ie(p),this.add(p.negate())}is0(){return this.equals(_.ZERO)}multiply(p){let{endo:g}=t;if(!o.isValidNot0(p))throw new RangeError("invalid scalar: out of range");let w,v,D=B=>_e.cached(this,B,k=>Ft(_,k));if(g){let{k1neg:B,k1:k,k2neg:E,k2:S}=Re(p),{p:T,f:G}=D(k),{p:P,f:O}=D(S);v=G.add(O),w=ar(g.beta,T,P,B,E)}else{let{p:B,f:k}=D(p);w=B,v=k}return Ft(_,[w,v])[0]}multiplyUnsafe(p){let{endo:g}=t,w=this,v=p;if(!o.isValid(v))throw new RangeError("invalid scalar: out of range");if(v===pe||w.is0())return _.ZERO;if(v===He)return w;if(_e.hasCache(this))return this.multiply(v);if(g){let{k1neg:D,k1:B,k2neg:k,k2:E}=Re(v),{p1:S,p2:T}=zr(_,w,B,E);return ar(g.beta,S,T,D,k)}else return _e.unsafe(w,v)}toAffine(p){let g=this,w=p,{X:v,Y:D,Z:B}=g;if(n.eql(B,n.ONE))return{x:v,y:D};let k=g.is0();w==null&&(w=k?n.ONE:n.inv(B));let E=n.mul(v,w),S=n.mul(D,w),T=n.mul(B,w);if(k)return{x:n.ZERO,y:n.ZERO};if(!n.eql(T,n.ONE))throw new Error("invZ was invalid");return{x:E,y:S}}isTorsionFree(){let{isTorsionFree:p}=t;return i===He?!0:p?p(_,this):_e.unsafe(this,a).is0()}clearCofactor(){let{clearCofactor:p}=t;return i===He?this:p?p(_,this):this.multiplyUnsafe(i)}isSmallOrder(){return i===He?this.is0():this.clearCofactor().is0()}toBytes(p=!0){return Oe(p,"isCompressed"),this.assertValidity(),A(_,this,p)}toHex(p=!0){return Er(this.toBytes(p))}toString(){return`<Point ${this.is0()?"ZERO":this.toHex()}>`}}let vt=o.BITS,_e=new et(_,t.endo?Math.ceil(vt/2):vt);return vt>=8&&_.BASE.precompute(8),Object.freeze(_.prototype),Object.freeze(_),_}function _o(e){return Uint8Array.of(e?2:3)}function Do(e,t){return{secretKey:t.BYTES,publicKey:1+e.BYTES,publicKeyUncompressed:1+2*e.BYTES,publicKeyHasPrefix:!0,signature:2*t.BYTES}}var ot={p:BigInt("0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f"),n:BigInt("0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141"),h:BigInt(1),a:BigInt(0),b:BigInt(7),Gx:BigInt("0x79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"),Gy:BigInt("0x483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8")},Oo={beta:BigInt("0x7ae96a2b657c07106e64479eac3434e99cf0497512f58995c1396c28719501ee"),basises:[[BigInt("0x3086d221a7d46bcde86c90e49284eb15"),-BigInt("0xe4437ed6010e88286f547fa90abfe4c3")],[BigInt("0x114ca50f7a8e2f3f657c1108d9d44cfd8"),BigInt("0x3086d221a7d46bcde86c90e49284eb15")]]},Co=BigInt(0),jt=BigInt(2);function Lo(e){let t=ot.p,r=BigInt(3),n=BigInt(6),o=BigInt(11),s=BigInt(22),i=BigInt(23),a=BigInt(44),c=BigInt(88),l=e*e*e%t,u=l*l*e%t,f=$(u,r,t)*u%t,b=$(f,r,t)*u%t,x=$(b,jt,t)*l%t,A=$(x,o,t)*x%t,I=$(A,s,t)*A%t,L=$(I,a,t)*I%t,j=$(L,c,t)*L%t,ye=$(j,a,t)*I%t,Et=$(ye,r,t)*u%t,Te=$(Et,i,t)*A%t,Ie=$(Te,n,t)*l%t,Re=$(Ie,jt,t);if(!rt.eql(rt.sqr(Re),e))throw new Error("Cannot find square root");return Re}var rt=xe(ot.p,{sqrt:Lo}),ve=Kr(ot,{Fp:rt,endo:Oo});var Wr={};function nt(e,...t){let r=Wr[e];if(r===void 0){let n=Rt(Sr(e));r=me(n,n),Wr[e]=r}return Rt(me(r,...t))}var st=e=>e.toBytes(!0).slice(1),it=e=>e%jt===Co;function Zr(e){let{Fn:t,BASE:r}=ve,n=t.fromBytes(e),o=r.multiply(n);return{scalar:it(o.y)?n:t.neg(n),bytes:st(o)}}function Jr(e){let t=rt;if(!t.isValidNot0(e))throw new Error("invalid x: Fail if x \u2265 p");let r=t.create(e*e),n=t.create(r*e+BigInt(7)),o=t.sqrt(n);it(o)||(o=t.neg(o));let s=ve.fromAffine({x:e,y:o});return s.assertValidity(),s}var Ee=fe;function Xr(...e){return ve.Fn.create(Ee(nt("BIP0340/challenge",...e)))}function Yr(e){return Zr(e).bytes}function No(e,t,r=Ge(32)){let{Fn:n,BASE:o}=ve,s=M(e,void 0,"message"),{bytes:i,scalar:a}=Zr(t),c=M(r,32,"auxRand"),l=n.toBytes(a^Ee(nt("BIP0340/aux",c))),u=nt("BIP0340/nonce",l,i,s),f=n.create(Ee(u));if(f===0n)throw new Error("sign failed: k is zero");let b=o.multiply(f),x=it(b.y)?f:n.neg(f),A=st(b),I=Xr(A,i,s),L=new Uint8Array(64);if(L.set(A,0),L.set(n.toBytes(n.create(x+I*a)),32),!Qr(L,s,i))throw new Error("sign: Invalid signature produced");return L}function Qr(e,t,r){let{Fp:n,Fn:o,BASE:s}=ve,i=M(e,64,"signature"),a=M(t,void 0,"message"),c=M(r,32,"publicKey");try{let l=Jr(Ee(c)),u=Ee(i.subarray(0,32));if(!n.isValidNot0(u))return!1;let f=Ee(i.subarray(32,64));if(!o.isValidNot0(f))return!1;let b=Xr(o.toBytes(u),st(l),a),x=s.multiplyUnsafe(f).add(l.multiplyUnsafe(o.neg(b))),{x:A,y:I}=x.toAffine();return!(x.is0()||!it(I)||A!==u)}catch{return!1}}var at=(()=>{let r=n=>(n=n===void 0?Ge(48):n,Pr(n,ot.n));return Object.freeze({keygen:Vt(r,Yr),getPublicKey:Yr,sign:No,verify:Qr,Point:ve,utils:Object.freeze({randomSecretKey:r,taggedHash:nt,lift_x:Jr,pointToBytes:st}),lengths:Object.freeze({secretKey:32,publicKey:32,publicKeyHasPrefix:!1,signature:64,seed:48})})})();d();function Uo(e){return e instanceof Uint8Array||ArrayBuffer.isView(e)&&e.constructor.name==="Uint8Array"}function Ae(e,t,r=""){let n=Uo(e),o=e?.length,s=t!==void 0;if(!n||s&&o!==t){let i=r&&`"${r}" `,a=s?` of length ${t}`:"",c=n?`length=${o}`:`type=${typeof e}`;throw new Error(i+"expected Uint8Array"+a+", got "+c)}return e}function qt(e,t=!0){if(e.destroyed)throw new Error("Hash instance has been destroyed");if(t&&e.finished)throw new Error("Hash#digest() has already been called")}function tn(e,t){Ae(e,void 0,"digestInto() output");let r=t.outputLen;if(e.length<r)throw new Error('"digestInto() output" expected to be of length >='+r)}function Pe(...e){for(let t=0;t<e.length;t++)e[t].fill(0)}function ct(e){return new DataView(e.buffer,e.byteOffset,e.byteLength)}function J(e,t){return e<<32-t|e>>>t}var rn=typeof Uint8Array.from([]).toHex=="function"&&typeof Uint8Array.fromHex=="function",Ho=Array.from({length:256},(e,t)=>t.toString(16).padStart(2,"0"));function nn(e){if(Ae(e),rn)return e.toHex();let t="";for(let r=0;r<e.length;r++)t+=Ho[e[r]];return t}var ne={_0:48,_9:57,A:65,F:70,a:97,f:102};function en(e){if(e>=ne._0&&e<=ne._9)return e-ne._0;if(e>=ne.A&&e<=ne.F)return e-(ne.A-10);if(e>=ne.a&&e<=ne.f)return e-(ne.a-10)}function on(e){if(typeof e!="string")throw new Error("hex string expected, got "+typeof e);if(rn)return Uint8Array.fromHex(e);let t=e.length,r=t/2;if(t%2)throw new Error("hex string expected, got unpadded hex of length "+t);let n=new Uint8Array(r);for(let o=0,s=0;o<r;o++,s+=2){let i=en(e.charCodeAt(s)),a=en(e.charCodeAt(s+1));if(i===void 0||a===void 0){let c=e[s]+e[s+1];throw new Error('hex string expected, got non-hex character "'+c+'" at index '+s)}n[o]=i*16+a}return n}function sn(e,t={}){let r=(o,s)=>e(s).update(o).digest(),n=e(void 0);return r.outputLen=n.outputLen,r.blockLen=n.blockLen,r.create=o=>e(o),Object.assign(r,t),Object.freeze(r)}var an=e=>({oid:Uint8Array.from([6,9,96,134,72,1,101,3,4,2,e])});d();d();function cn(e,t,r){return e&t^~e&r}function ln(e,t,r){return e&t^e&r^t&r}var lt=class{blockLen;outputLen;padOffset;isLE;buffer;view;finished=!1;length=0;pos=0;destroyed=!1;constructor(t,r,n,o){this.blockLen=t,this.outputLen=r,this.padOffset=n,this.isLE=o,this.buffer=new Uint8Array(t),this.view=ct(this.buffer)}update(t){qt(this),Ae(t);let{view:r,buffer:n,blockLen:o}=this,s=t.length;for(let i=0;i<s;){let a=Math.min(o-this.pos,s-i);if(a===o){let c=ct(t);for(;o<=s-i;i+=o)this.process(c,i);continue}n.set(t.subarray(i,i+a),this.pos),this.pos+=a,i+=a,this.pos===o&&(this.process(r,0),this.pos=0)}return this.length+=t.length,this.roundClean(),this}digestInto(t){qt(this),tn(t,this),this.finished=!0;let{buffer:r,view:n,blockLen:o,isLE:s}=this,{pos:i}=this;r[i++]=128,Pe(this.buffer.subarray(i)),this.padOffset>o-i&&(this.process(n,0),i=0);for(let f=i;f<o;f++)r[f]=0;n.setBigUint64(o-8,BigInt(this.length*8),s),this.process(n,0);let a=ct(t),c=this.outputLen;if(c%4)throw new Error("_sha2: outputLen must be aligned to 32bit");let l=c/4,u=this.get();if(l>u.length)throw new Error("_sha2: outputLen bigger than state");for(let f=0;f<l;f++)a.setUint32(4*f,u[f],s)}digest(){let{buffer:t,outputLen:r}=this;this.digestInto(t);let n=t.slice(0,r);return this.destroy(),n}_cloneInto(t){t||=new this.constructor,t.set(...this.get());let{blockLen:r,buffer:n,length:o,finished:s,destroyed:i,pos:a}=this;return t.destroyed=i,t.finished=s,t.length=o,t.pos=a,o%r&&t.buffer.set(n),t}clone(){return this._cloneInto()}},oe=Uint32Array.from([1779033703,3144134277,1013904242,2773480762,1359893119,2600822924,528734635,1541459225]);var Po=Uint32Array.from([1116352408,1899447441,3049323471,3921009573,961987163,1508970993,2453635748,2870763221,3624381080,310598401,607225278,1426881987,1925078388,2162078206,2614888103,3248222580,3835390401,4022224774,264347078,604807628,770255983,1249150122,1555081692,1996064986,2554220882,2821834349,2952996808,3210313671,3336571891,3584528711,113926993,338241895,666307205,773529912,1294757372,1396182291,1695183700,1986661051,2177026350,2456956037,2730485921,2820302411,3259730800,3345764771,3516065817,3600352804,4094571909,275423344,430227734,506948616,659060556,883997877,958139571,1322822218,1537002063,1747873779,1955562222,2024104815,2227730452,2361852424,2428436474,2756734187,3204031479,3329325298]),ce=new Uint32Array(64),zt=class extends lt{constructor(t){super(64,t,8,!1)}get(){let{A:t,B:r,C:n,D:o,E:s,F:i,G:a,H:c}=this;return[t,r,n,o,s,i,a,c]}set(t,r,n,o,s,i,a,c){this.A=t|0,this.B=r|0,this.C=n|0,this.D=o|0,this.E=s|0,this.F=i|0,this.G=a|0,this.H=c|0}process(t,r){for(let f=0;f<16;f++,r+=4)ce[f]=t.getUint32(r,!1);for(let f=16;f<64;f++){let b=ce[f-15],x=ce[f-2],A=J(b,7)^J(b,18)^b>>>3,I=J(x,17)^J(x,19)^x>>>10;ce[f]=I+ce[f-7]+A+ce[f-16]|0}let{A:n,B:o,C:s,D:i,E:a,F:c,G:l,H:u}=this;for(let f=0;f<64;f++){let b=J(a,6)^J(a,11)^J(a,25),x=u+b+cn(a,c,l)+Po[f]+ce[f]|0,I=(J(n,2)^J(n,13)^J(n,22))+ln(n,o,s)|0;u=l,l=c,c=a,a=i+x|0,i=s,s=o,o=n,n=x+I|0}n=n+this.A|0,o=o+this.B|0,s=s+this.C|0,i=i+this.D|0,a=a+this.E|0,c=c+this.F|0,l=l+this.G|0,u=u+this.H|0,this.set(n,o,s,i,a,c,l,u)}roundClean(){Pe(ce)}destroy(){this.set(0,0,0,0,0,0,0,0),Pe(this.buffer)}},$t=class extends zt{A=oe[0]|0;B=oe[1]|0;C=oe[2]|0;D=oe[3]|0;E=oe[4]|0;F=oe[5]|0;G=oe[6]|0;H=oe[7]|0;constructor(){super(32)}};var fn=sn(()=>new $t,an(1));d();var un;(function(e){e[e.DEBUG=0]="DEBUG",e[e.INFO=1]="INFO",e[e.WARN=2]="WARN",e[e.ERROR=3]="ERROR"})(un||(un={}));var Gt=["trace","debug","info","warn","error","fatal","silent"];function Fo(){let t=((typeof m<"u"&&m.env?m.env:{}).LOG_LEVEL||"info").toLowerCase();return Gt.includes(t)?t:"info"}function dn(e){let t=Gt.indexOf(e);return t===-1?Gt.indexOf("info"):t}function pn(e){return e instanceof Error?{name:e.name,message:e.message,stack:e.stack}:e}var hn={trace:(console.debug??console.log).bind(console),debug:(console.debug??console.log).bind(console),info:(console.info??console.log).bind(console),warn:(console.warn??console.log).bind(console),error:(console.error??console.log).bind(console),fatal:(console.error??console.log).bind(console),silent:()=>{}},Kt=class e{level;name;bindings;constructor(t={}){this.name=t.name,this.level=t.level||Fo(),this.bindings=t.bindings??{}}emit(t,r){if(this.level==="silent"||dn(t)<dn(this.level))return;let n,o;if(r.length&&typeof r[0]=="object"&&r[0]!==null){n={};for(let[c,l]of Object.entries(r[0]))n[c]=pn(l);o=r[1]!=null?String(r[1]):""}else o=r.map(c=>typeof c=="string"?c:JSON.stringify(pn(c))).join(" ");let s={...this.bindings,...n},i=`[${new Date().toISOString()}] ${t.toUpperCase()}`+(this.name?` (${this.name})`:""),a=Object.keys(s).length?` ${JSON.stringify(s)}`:"";(hn[t]??hn.info)(`${i}: ${o}${a}`)}trace(...t){this.emit("trace",t)}debug(...t){this.emit("debug",t)}info(...t){this.emit("info",t)}warn(...t){this.emit("warn",t)}error(...t){this.emit("error",t)}fatal(...t){this.emit("fatal",t)}child(t){return new e({name:this.name,level:this.level,bindings:{...this.bindings,...t}})}};var he=new Kt({name:"nostr-crypto-utils"});var Mo=async()=>{if(typeof window<"u"&&window.crypto)return window.crypto;if(typeof globalThis<"u"&&globalThis.crypto)return globalThis.crypto;try{let e=await Promise.resolve().then(()=>fr(bn(),1));if(e.webcrypto)return e.webcrypto}catch{he.debug("Node crypto not available")}throw new Error("No WebCrypto implementation available")},Wt=class{cryptoInstance=null;initPromise;constructor(){this.initPromise=this.initialize()}async initialize(){this.cryptoInstance=await Mo()}async ensureInitialized(){if(await this.initPromise,!this.cryptoInstance)throw new Error("Crypto implementation not initialized");return this.cryptoInstance}async getSubtle(){return(await this.ensureInitialized()).subtle}async getRandomValues(t){return(await this.ensureInitialized()).getRandomValues(t)}},La=new Wt,jo=at.sign,qo=at.verify;function Fe(e){let t=e instanceof Uint8Array?e:on(e),r=at.getPublicKey(t);return nn(r)}d();d();d();d();d();d();var ac=new TextEncoder,cc=new TextDecoder;d();d();var Xo=fr(vn(),1);var yc=new TextEncoder,bc=new TextDecoder;d();d();d();function ut(e){return e instanceof Uint8Array||ArrayBuffer.isView(e)&&e.constructor.name==="Uint8Array"}function An(e,t){return Array.isArray(t)?t.length===0?!0:e?t.every(r=>typeof r=="string"):t.every(r=>Number.isSafeInteger(r)):!1}function ts(e){if(typeof e!="function")throw new Error("function expected");return!0}function dt(e,t){if(typeof t!="string")throw new Error(`${e}: string expected`);return!0}function ke(e){if(!Number.isSafeInteger(e))throw new Error(`invalid integer: ${e}`)}function pt(e){if(!Array.isArray(e))throw new Error("array expected")}function ht(e,t){if(!An(!0,t))throw new Error(`${e}: array of strings expected`)}function Sn(e,t){if(!An(!1,t))throw new Error(`${e}: array of numbers expected`)}function rs(...e){let t=s=>s,r=(s,i)=>a=>s(i(a)),n=e.map(s=>s.encode).reduceRight(r,t),o=e.map(s=>s.decode).reduce(r,t);return{encode:n,decode:o}}function ns(e){let t=typeof e=="string"?e.split(""):e,r=t.length;ht("alphabet",t);let n=new Map(t.map((o,s)=>[o,s]));return{encode:o=>(pt(o),o.map(s=>{if(!Number.isSafeInteger(s)||s<0||s>=r)throw new Error(`alphabet.encode: digit index outside alphabet "${s}". Allowed: ${e}`);return t[s]})),decode:o=>(pt(o),o.map(s=>{dt("alphabet.decode",s);let i=n.get(s);if(i===void 0)throw new Error(`Unknown letter: "${s}". Allowed: ${e}`);return i}))}}function os(e=""){return dt("join",e),{encode:t=>(ht("join.decode",t),t.join(e)),decode:t=>(dt("join.decode",t),t.split(e))}}function ss(e,t="="){return ke(e),dt("padding",t),{encode(r){for(ht("padding.encode",r);r.length*e%8;)r.push(t);return r},decode(r){ht("padding.decode",r);let n=r.length;if(n*e%8)throw new Error("padding: invalid, string should have whole number of bytes");for(;n>0&&r[n-1]===t;n--)if((n-1)*e%8===0)throw new Error("padding: invalid, string has too much padding");return r.slice(0,n)}}}function Jt(e,t,r){if(t<2)throw new Error(`convertRadix: invalid from=${t}, base cannot be less than 2`);if(r<2)throw new Error(`convertRadix: invalid to=${r}, base cannot be less than 2`);if(pt(e),!e.length)return[];let n=0,o=[],s=Array.from(e,a=>{if(ke(a),a<0||a>=t)throw new Error(`invalid integer: ${a}`);return a}),i=s.length;for(;;){let a=0,c=!0;for(let l=n;l<i;l++){let u=s[l],f=t*a,b=f+u;if(!Number.isSafeInteger(b)||f/t!==a||b-u!==f)throw new Error("convertRadix: carry overflow");let x=b/r;a=b%r;let A=Math.floor(x);if(s[l]=A,!Number.isSafeInteger(A)||A*r+a!==b)throw new Error("convertRadix: carry overflow");if(c)A?c=!1:n=l;else continue}if(o.push(a),c)break}for(let a=0;a<e.length-1&&e[a]===0;a++)o.push(0);return o.reverse()}var Bn=(e,t)=>t===0?e:Bn(t,e%t),yt=(e,t)=>e+(t-Bn(e,t)),Zt=(()=>{let e=[];for(let t=0;t<40;t++)e.push(2**t);return e})();function Xt(e,t,r,n){if(pt(e),t<=0||t>32)throw new Error(`convertRadix2: wrong from=${t}`);if(r<=0||r>32)throw new Error(`convertRadix2: wrong to=${r}`);if(yt(t,r)>32)throw new Error(`convertRadix2: carry overflow from=${t} to=${r} carryBits=${yt(t,r)}`);let o=0,s=0,i=Zt[t],a=Zt[r]-1,c=[];for(let l of e){if(ke(l),l>=i)throw new Error(`convertRadix2: invalid data word=${l} from=${t}`);if(o=o<<t|l,s+t>32)throw new Error(`convertRadix2: carry overflow pos=${s} from=${t}`);for(s+=t;s>=r;s-=r)c.push((o>>s-r&a)>>>0);let u=Zt[s];if(u===void 0)throw new Error("invalid carry");o&=u-1}if(o=o<<r-s&a,!n&&s>=t)throw new Error("Excess padding");if(!n&&o>0)throw new Error(`Non-zero padding: ${o}`);return n&&s>0&&c.push(o>>>0),c}function is(e){ke(e);let t=2**8;return{encode:r=>{if(!ut(r))throw new Error("radix.encode input should be Uint8Array");return Jt(Array.from(r),t,e)},decode:r=>(Sn("radix.decode",r),Uint8Array.from(Jt(r,e,t)))}}function as(e,t=!1){if(ke(e),e<=0||e>32)throw new Error("radix2: bits should be in (0..32]");if(yt(8,e)>32||yt(e,8)>32)throw new Error("radix2: carry overflow");return{encode:r=>{if(!ut(r))throw new Error("radix2.encode input should be Uint8Array");return Xt(Array.from(r),8,e,!t)},decode:r=>(Sn("radix2.decode",r),Uint8Array.from(Xt(r,e,8,t)))}}function cs(e,t){return ke(e),ts(t),{encode(r){if(!ut(r))throw new Error("checksum.encode: input should be Uint8Array");let n=t(r).slice(0,e),o=new Uint8Array(r.length+e);return o.set(r),o.set(n,r.length),o},decode(r){if(!ut(r))throw new Error("checksum.decode: input should be Uint8Array");let n=r.slice(0,-e),o=r.slice(-e),s=t(n).slice(0,e);for(let i=0;i<e;i++)if(s[i]!==o[i])throw new Error("Invalid checksum");return n}}}var Ve={alphabet:ns,chain:rs,checksum:cs,convertRadix:Jt,convertRadix2:Xt,radix:is,radix2:as,join:os,padding:ss};var vc=new TextEncoder,Ac=new TextDecoder;d();d();d();var Oc=2880*60;d();d();var Mc=new TextEncoder,jc=new TextDecoder;d();d();function Qt(e){let t=new Uint8Array(e),r="";for(let n=0;n<t.length;n++)r+=String.fromCharCode(t[n]);return btoa(r)}async function In(e,t,r){let n=crypto.getRandomValues(new Uint8Array(12)),o=new TextEncoder,s=await crypto.subtle.encrypt({name:"AES-GCM",iv:n},t,o.encode(e));return JSON.stringify({salt:Qt(r),iv:Qt(n),ciphertext:Qt(s)})}d();d();function Es(e){if(typeof e!="string")throw new TypeError("invalid mnemonic type: "+typeof e);return e.normalize("NFKD")}function vs(e){let t=Es(e),r=t.split(" ");if(![12,15,18,21,24].includes(r.length))throw new Error("Invalid mnemonic");return{nfkd:t,words:r}}function As(e){if(Ae(e),![16,20,24,28,32].includes(e.length))throw new Error("invalid entropy length")}var Ss=e=>{let t=8-e.length/4;return new Uint8Array([fn(e)[0]>>t<<t])};function Bs(e){if(!Array.isArray(e)||e.length!==2048||typeof e[0]!="string")throw new Error("Wordlist: expected array of 2048 strings");return e.forEach(t=>{if(typeof t!="string")throw new Error("wordlist: non-string element: "+t)}),Ve.chain(Ve.checksum(1,Ss),Ve.radix2(11,!0),Ve.alphabet(e))}function Rn(e,t){let{words:r}=vs(e),n=Bs(t).decode(r);return As(n),n}function _n(e,t){try{Rn(e,t)}catch{return!1}return!0}d();var Dn=`abandon
ability
able
about
above
absent
absorb
abstract
absurd
abuse
access
accident
account
accuse
achieve
acid
acoustic
acquire
across
act
action
actor
actress
actual
adapt
add
addict
address
adjust
admit
adult
advance
advice
aerobic
affair
afford
afraid
again
age
agent
agree
ahead
aim
air
airport
aisle
alarm
album
alcohol
alert
alien
all
alley
allow
almost
alone
alpha
already
also
alter
always
amateur
amazing
among
amount
amused
analyst
anchor
ancient
anger
angle
angry
animal
ankle
announce
annual
another
answer
antenna
antique
anxiety
any
apart
apology
appear
apple
approve
april
arch
arctic
area
arena
argue
arm
armed
armor
army
around
arrange
arrest
arrive
arrow
art
artefact
artist
artwork
ask
aspect
assault
asset
assist
assume
asthma
athlete
atom
attack
attend
attitude
attract
auction
audit
august
aunt
author
auto
autumn
average
avocado
avoid
awake
aware
away
awesome
awful
awkward
axis
baby
bachelor
bacon
badge
bag
balance
balcony
ball
bamboo
banana
banner
bar
barely
bargain
barrel
base
basic
basket
battle
beach
bean
beauty
because
become
beef
before
begin
behave
behind
believe
below
belt
bench
benefit
best
betray
better
between
beyond
bicycle
bid
bike
bind
biology
bird
birth
bitter
black
blade
blame
blanket
blast
bleak
bless
blind
blood
blossom
blouse
blue
blur
blush
board
boat
body
boil
bomb
bone
bonus
book
boost
border
boring
borrow
boss
bottom
bounce
box
boy
bracket
brain
brand
brass
brave
bread
breeze
brick
bridge
brief
bright
bring
brisk
broccoli
broken
bronze
broom
brother
brown
brush
bubble
buddy
budget
buffalo
build
bulb
bulk
bullet
bundle
bunker
burden
burger
burst
bus
business
busy
butter
buyer
buzz
cabbage
cabin
cable
cactus
cage
cake
call
calm
camera
camp
can
canal
cancel
candy
cannon
canoe
canvas
canyon
capable
capital
captain
car
carbon
card
cargo
carpet
carry
cart
case
cash
casino
castle
casual
cat
catalog
catch
category
cattle
caught
cause
caution
cave
ceiling
celery
cement
census
century
cereal
certain
chair
chalk
champion
change
chaos
chapter
charge
chase
chat
cheap
check
cheese
chef
cherry
chest
chicken
chief
child
chimney
choice
choose
chronic
chuckle
chunk
churn
cigar
cinnamon
circle
citizen
city
civil
claim
clap
clarify
claw
clay
clean
clerk
clever
click
client
cliff
climb
clinic
clip
clock
clog
close
cloth
cloud
clown
club
clump
cluster
clutch
coach
coast
coconut
code
coffee
coil
coin
collect
color
column
combine
come
comfort
comic
common
company
concert
conduct
confirm
congress
connect
consider
control
convince
cook
cool
copper
copy
coral
core
corn
correct
cost
cotton
couch
country
couple
course
cousin
cover
coyote
crack
cradle
craft
cram
crane
crash
crater
crawl
crazy
cream
credit
creek
crew
cricket
crime
crisp
critic
crop
cross
crouch
crowd
crucial
cruel
cruise
crumble
crunch
crush
cry
crystal
cube
culture
cup
cupboard
curious
current
curtain
curve
cushion
custom
cute
cycle
dad
damage
damp
dance
danger
daring
dash
daughter
dawn
day
deal
debate
debris
decade
december
decide
decline
decorate
decrease
deer
defense
define
defy
degree
delay
deliver
demand
demise
denial
dentist
deny
depart
depend
deposit
depth
deputy
derive
describe
desert
design
desk
despair
destroy
detail
detect
develop
device
devote
diagram
dial
diamond
diary
dice
diesel
diet
differ
digital
dignity
dilemma
dinner
dinosaur
direct
dirt
disagree
discover
disease
dish
dismiss
disorder
display
distance
divert
divide
divorce
dizzy
doctor
document
dog
doll
dolphin
domain
donate
donkey
donor
door
dose
double
dove
draft
dragon
drama
drastic
draw
dream
dress
drift
drill
drink
drip
drive
drop
drum
dry
duck
dumb
dune
during
dust
dutch
duty
dwarf
dynamic
eager
eagle
early
earn
earth
easily
east
easy
echo
ecology
economy
edge
edit
educate
effort
egg
eight
either
elbow
elder
electric
elegant
element
elephant
elevator
elite
else
embark
embody
embrace
emerge
emotion
employ
empower
empty
enable
enact
end
endless
endorse
enemy
energy
enforce
engage
engine
enhance
enjoy
enlist
enough
enrich
enroll
ensure
enter
entire
entry
envelope
episode
equal
equip
era
erase
erode
erosion
error
erupt
escape
essay
essence
estate
eternal
ethics
evidence
evil
evoke
evolve
exact
example
excess
exchange
excite
exclude
excuse
execute
exercise
exhaust
exhibit
exile
exist
exit
exotic
expand
expect
expire
explain
expose
express
extend
extra
eye
eyebrow
fabric
face
faculty
fade
faint
faith
fall
false
fame
family
famous
fan
fancy
fantasy
farm
fashion
fat
fatal
father
fatigue
fault
favorite
feature
february
federal
fee
feed
feel
female
fence
festival
fetch
fever
few
fiber
fiction
field
figure
file
film
filter
final
find
fine
finger
finish
fire
firm
first
fiscal
fish
fit
fitness
fix
flag
flame
flash
flat
flavor
flee
flight
flip
float
flock
floor
flower
fluid
flush
fly
foam
focus
fog
foil
fold
follow
food
foot
force
forest
forget
fork
fortune
forum
forward
fossil
foster
found
fox
fragile
frame
frequent
fresh
friend
fringe
frog
front
frost
frown
frozen
fruit
fuel
fun
funny
furnace
fury
future
gadget
gain
galaxy
gallery
game
gap
garage
garbage
garden
garlic
garment
gas
gasp
gate
gather
gauge
gaze
general
genius
genre
gentle
genuine
gesture
ghost
giant
gift
giggle
ginger
giraffe
girl
give
glad
glance
glare
glass
glide
glimpse
globe
gloom
glory
glove
glow
glue
goat
goddess
gold
good
goose
gorilla
gospel
gossip
govern
gown
grab
grace
grain
grant
grape
grass
gravity
great
green
grid
grief
grit
grocery
group
grow
grunt
guard
guess
guide
guilt
guitar
gun
gym
habit
hair
half
hammer
hamster
hand
happy
harbor
hard
harsh
harvest
hat
have
hawk
hazard
head
health
heart
heavy
hedgehog
height
hello
helmet
help
hen
hero
hidden
high
hill
hint
hip
hire
history
hobby
hockey
hold
hole
holiday
hollow
home
honey
hood
hope
horn
horror
horse
hospital
host
hotel
hour
hover
hub
huge
human
humble
humor
hundred
hungry
hunt
hurdle
hurry
hurt
husband
hybrid
ice
icon
idea
identify
idle
ignore
ill
illegal
illness
image
imitate
immense
immune
impact
impose
improve
impulse
inch
include
income
increase
index
indicate
indoor
industry
infant
inflict
inform
inhale
inherit
initial
inject
injury
inmate
inner
innocent
input
inquiry
insane
insect
inside
inspire
install
intact
interest
into
invest
invite
involve
iron
island
isolate
issue
item
ivory
jacket
jaguar
jar
jazz
jealous
jeans
jelly
jewel
job
join
joke
journey
joy
judge
juice
jump
jungle
junior
junk
just
kangaroo
keen
keep
ketchup
key
kick
kid
kidney
kind
kingdom
kiss
kit
kitchen
kite
kitten
kiwi
knee
knife
knock
know
lab
label
labor
ladder
lady
lake
lamp
language
laptop
large
later
latin
laugh
laundry
lava
law
lawn
lawsuit
layer
lazy
leader
leaf
learn
leave
lecture
left
leg
legal
legend
leisure
lemon
lend
length
lens
leopard
lesson
letter
level
liar
liberty
library
license
life
lift
light
like
limb
limit
link
lion
liquid
list
little
live
lizard
load
loan
lobster
local
lock
logic
lonely
long
loop
lottery
loud
lounge
love
loyal
lucky
luggage
lumber
lunar
lunch
luxury
lyrics
machine
mad
magic
magnet
maid
mail
main
major
make
mammal
man
manage
mandate
mango
mansion
manual
maple
marble
march
margin
marine
market
marriage
mask
mass
master
match
material
math
matrix
matter
maximum
maze
meadow
mean
measure
meat
mechanic
medal
media
melody
melt
member
memory
mention
menu
mercy
merge
merit
merry
mesh
message
metal
method
middle
midnight
milk
million
mimic
mind
minimum
minor
minute
miracle
mirror
misery
miss
mistake
mix
mixed
mixture
mobile
model
modify
mom
moment
monitor
monkey
monster
month
moon
moral
more
morning
mosquito
mother
motion
motor
mountain
mouse
move
movie
much
muffin
mule
multiply
muscle
museum
mushroom
music
must
mutual
myself
mystery
myth
naive
name
napkin
narrow
nasty
nation
nature
near
neck
need
negative
neglect
neither
nephew
nerve
nest
net
network
neutral
never
news
next
nice
night
noble
noise
nominee
noodle
normal
north
nose
notable
note
nothing
notice
novel
now
nuclear
number
nurse
nut
oak
obey
object
oblige
obscure
observe
obtain
obvious
occur
ocean
october
odor
off
offer
office
often
oil
okay
old
olive
olympic
omit
once
one
onion
online
only
open
opera
opinion
oppose
option
orange
orbit
orchard
order
ordinary
organ
orient
original
orphan
ostrich
other
outdoor
outer
output
outside
oval
oven
over
own
owner
oxygen
oyster
ozone
pact
paddle
page
pair
palace
palm
panda
panel
panic
panther
paper
parade
parent
park
parrot
party
pass
patch
path
patient
patrol
pattern
pause
pave
payment
peace
peanut
pear
peasant
pelican
pen
penalty
pencil
people
pepper
perfect
permit
person
pet
phone
photo
phrase
physical
piano
picnic
picture
piece
pig
pigeon
pill
pilot
pink
pioneer
pipe
pistol
pitch
pizza
place
planet
plastic
plate
play
please
pledge
pluck
plug
plunge
poem
poet
point
polar
pole
police
pond
pony
pool
popular
portion
position
possible
post
potato
pottery
poverty
powder
power
practice
praise
predict
prefer
prepare
present
pretty
prevent
price
pride
primary
print
priority
prison
private
prize
problem
process
produce
profit
program
project
promote
proof
property
prosper
protect
proud
provide
public
pudding
pull
pulp
pulse
pumpkin
punch
pupil
puppy
purchase
purity
purpose
purse
push
put
puzzle
pyramid
quality
quantum
quarter
question
quick
quit
quiz
quote
rabbit
raccoon
race
rack
radar
radio
rail
rain
raise
rally
ramp
ranch
random
range
rapid
rare
rate
rather
raven
raw
razor
ready
real
reason
rebel
rebuild
recall
receive
recipe
record
recycle
reduce
reflect
reform
refuse
region
regret
regular
reject
relax
release
relief
rely
remain
remember
remind
remove
render
renew
rent
reopen
repair
repeat
replace
report
require
rescue
resemble
resist
resource
response
result
retire
retreat
return
reunion
reveal
review
reward
rhythm
rib
ribbon
rice
rich
ride
ridge
rifle
right
rigid
ring
riot
ripple
risk
ritual
rival
river
road
roast
robot
robust
rocket
romance
roof
rookie
room
rose
rotate
rough
round
route
royal
rubber
rude
rug
rule
run
runway
rural
sad
saddle
sadness
safe
sail
salad
salmon
salon
salt
salute
same
sample
sand
satisfy
satoshi
sauce
sausage
save
say
scale
scan
scare
scatter
scene
scheme
school
science
scissors
scorpion
scout
scrap
screen
script
scrub
sea
search
season
seat
second
secret
section
security
seed
seek
segment
select
sell
seminar
senior
sense
sentence
series
service
session
settle
setup
seven
shadow
shaft
shallow
share
shed
shell
sheriff
shield
shift
shine
ship
shiver
shock
shoe
shoot
shop
short
shoulder
shove
shrimp
shrug
shuffle
shy
sibling
sick
side
siege
sight
sign
silent
silk
silly
silver
similar
simple
since
sing
siren
sister
situate
six
size
skate
sketch
ski
skill
skin
skirt
skull
slab
slam
sleep
slender
slice
slide
slight
slim
slogan
slot
slow
slush
small
smart
smile
smoke
smooth
snack
snake
snap
sniff
snow
soap
soccer
social
sock
soda
soft
solar
soldier
solid
solution
solve
someone
song
soon
sorry
sort
soul
sound
soup
source
south
space
spare
spatial
spawn
speak
special
speed
spell
spend
sphere
spice
spider
spike
spin
spirit
split
spoil
sponsor
spoon
sport
spot
spray
spread
spring
spy
square
squeeze
squirrel
stable
stadium
staff
stage
stairs
stamp
stand
start
state
stay
steak
steel
stem
step
stereo
stick
still
sting
stock
stomach
stone
stool
story
stove
strategy
street
strike
strong
struggle
student
stuff
stumble
style
subject
submit
subway
success
such
sudden
suffer
sugar
suggest
suit
summer
sun
sunny
sunset
super
supply
supreme
sure
surface
surge
surprise
surround
survey
suspect
sustain
swallow
swamp
swap
swarm
swear
sweet
swift
swim
swing
switch
sword
symbol
symptom
syrup
system
table
tackle
tag
tail
talent
talk
tank
tape
target
task
taste
tattoo
taxi
teach
team
tell
ten
tenant
tennis
tent
term
test
text
thank
that
theme
then
theory
there
they
thing
this
thought
three
thrive
throw
thumb
thunder
ticket
tide
tiger
tilt
timber
time
tiny
tip
tired
tissue
title
toast
tobacco
today
toddler
toe
together
toilet
token
tomato
tomorrow
tone
tongue
tonight
tool
tooth
top
topic
topple
torch
tornado
tortoise
toss
total
tourist
toward
tower
town
toy
track
trade
traffic
tragic
train
transfer
trap
trash
travel
tray
treat
tree
trend
trial
tribe
trick
trigger
trim
trip
trophy
trouble
truck
true
truly
trumpet
trust
truth
try
tube
tuition
tumble
tuna
tunnel
turkey
turn
turtle
twelve
twenty
twice
twin
twist
two
type
typical
ugly
umbrella
unable
unaware
uncle
uncover
under
undo
unfair
unfold
unhappy
uniform
unique
unit
universe
unknown
unlock
until
unusual
unveil
update
upgrade
uphold
upon
upper
upset
urban
urge
usage
use
used
useful
useless
usual
utility
vacant
vacuum
vague
valid
valley
valve
van
vanish
vapor
various
vast
vault
vehicle
velvet
vendor
venture
venue
verb
verify
version
very
vessel
veteran
viable
vibrant
vicious
victory
video
view
village
vintage
violin
virtual
virus
visa
visit
visual
vital
vivid
vocal
voice
void
volcano
volume
vote
voyage
wage
wagon
wait
walk
wall
walnut
want
warfare
warm
warrior
wash
wasp
waste
water
wave
way
wealth
weapon
wear
weasel
weather
web
wedding
weekend
weird
welcome
west
wet
whale
what
wheat
wheel
when
where
whip
whisper
wide
width
wife
wild
will
win
window
wine
wing
wink
winner
winter
wire
wisdom
wise
wish
witness
wolf
woman
wonder
wood
wool
word
work
world
worry
worth
wrap
wreck
wrestle
wrist
write
wrong
yard
year
yellow
you
young
youth
zebra
zero
zone
zoo`.split(`
`);function ks(e){return String(e||"").trim().toLowerCase().replace(/\s+/g," ")}function On(e){try{return _n(ks(e),Dn)}catch{return!1}}d();var Vs=12,Ms="nostrkey-secret-vault",gt="keys",jn="device-wrap-key-v1";function qn(e){let t=new Uint8Array(e),r="";for(let n=0;n<t.length;n++)r+=String.fromCharCode(t[n]);return btoa(r)}var zn=null,js=null;var xt=null,ir=null;async function $n(){return crypto.subtle.generateKey({name:"AES-GCM",length:256},!1,["encrypt","decrypt"])}function qs(){return typeof indexedDB<"u"&&indexedDB!==null}async function zs(){return xt||(xt=(async()=>{if(!qs())return ir||(ir=await $n()),ir;let{openDB:e}=await Promise.resolve().then(()=>(Mn(),Vn)),t=await e(Ms,1,{upgrade(n){n.objectStoreNames.contains(gt)||n.createObjectStore(gt)}}),r=await t.get(gt,jn);return r||(r=await $n(),await t.put(gt,r,jn)),r})(),xt)}async function $s(e){let t=await zs(),r=crypto.getRandomValues(new Uint8Array(Vs)),n=new TextEncoder,o=await crypto.subtle.encrypt({name:"AES-GCM",iv:r},t,n.encode(e));return JSON.stringify({v:1,k:"device",iv:qn(r),ciphertext:qn(o)})}function Gs(e){if(typeof e!="string")return!1;try{let t=JSON.parse(e);return!!(t&&t.salt&&t.iv&&t.ciphertext&&t.k!=="device")}catch{return!1}}function Gn(e){if(typeof e!="string")return!1;try{let t=JSON.parse(e);return!!(t&&t.k==="device"&&t.iv&&t.ciphertext)}catch{return!1}}function Kn(e){return Gs(e)||Gn(e)}async function Wn(e){return typeof e!="string"||e.length===0||Kn(e)?e:zn?In(e,zn,js):$s(e)}var Yn=6,q=z.storage.local,Ks=[new URL("wss://relay.damus.io"),new URL("wss://relay.primal.net"),new URL("wss://relay.snort.social"),new URL("wss://relay.getalby.com/v1"),new URL("wss://nos.lol")];async function Jn(){await Zn("profileIndex",0),await Zn("profiles",[await Qn()]);let e=(await q.get({version:0})).version;for(;e<Yn;)e=await Ws(e,Yn),await q.set({version:e})}async function Ws(e,t){if(e===0){let r=await le();return r.forEach(n=>n.hosts={}),await q.set({profiles:r}),e+1}if(e===1){let r=await le();return await q.set({profiles:r}),e+1}if(e===2){let r=await le();return r.forEach(n=>n.relayReminder=!0),await q.set({profiles:r}),e+1}if(e===3)return(await q.get({isEncrypted:!1})).isEncrypted||await q.set({isEncrypted:!1}),e+1;if(e===4){let r=await le();return r.forEach(n=>{n.type||(n.type="local"),n.bunkerUrl===void 0&&(n.bunkerUrl=null),n.remotePubkey===void 0&&(n.remotePubkey=null)}),await q.set({profiles:r}),e+1}if(e===5){let r=Math.floor(Date.now()/1e3),n=await le();return n.forEach(o=>{o.updatedAt===void 0&&(o.updatedAt=r)}),await q.set({profiles:n,platformSyncEnabled:!0}),e+1}}async function le(){return(await q.get({profiles:[]})).profiles}async function Xn(){return(await le()).map(t=>t.name)}async function Ys(){return await z.runtime.sendMessage({kind:"generatePrivateKey"})}async function Qn(e="Default Nostr Profile",t="local"){let r="",n="";if(t==="local"){let o=await Ys();try{n=Fe(o)}catch{}r=await Wn(o)}return{name:e,privKey:r,pubKey:n,hosts:{},relays:Ks.map(o=>({url:o.href,read:!0,write:!0})),relayReminder:!1,type:t,bunkerUrl:null,remotePubkey:null,updatedAt:Math.floor(Date.now()/1e3)}}async function Zn(e,t){let r=(await q.get(e))[e];return r==null||r==null?(await q.set({[e]:t}),t):r}async function eo(e,t){let r=await le();r[e].name=t,r[e].updatedAt=Math.floor(Date.now()/1e3),await q.set({profiles:r})}async function to(e,t){await z.runtime.sendMessage({kind:"savePrivateKey",payload:[e,t]})}async function ro(){let e=await le(),t=await Qn("New Profile");return e.push(t),await q.set({profiles:e}),e.length-1}function no(e){let t=/^[\da-f]{64}$/i.test(e),r=/^nsec1[qpzry9x8gf2tvdw0s3jn54khce6mua7l]{58}$/.test(e);return t||r||Zs(e)||On(e)}function Zs(e){return/^ncryptsec1[qpzry9x8gf2tvdw0s3jn54khce6mua7l]+$/.test(e)}var y={profiles:[],selectedIndex:null,nsecVisible:!1,nsecValue:"",npubValue:"",showImport:!1,importData:"",importName:"",importError:"",toast:""};function R(e){return document.getElementById(e)}function Js(e){return!e||e.length<=20?e||"":e.slice(0,12)+"\u2026"+e.slice(-8)}function wt(e){y.toast=e,X(),setTimeout(()=>{y.toast="",X()},2e3)}function Xs(e){let t=document.createElement("div");return t.textContent=e,t.innerHTML}function X(){let e=R("profile-list"),t=R("no-profiles"),r=R("profile-count"),n=R("detail-empty"),o=R("detail-panel"),s=R("import-panel");r&&(r.textContent=y.profiles.length+" profile"+(y.profiles.length!==1?"s":"")),e&&(e.innerHTML=y.profiles.map(u=>`
            <div class="profile-item ${y.selectedIndex===u.index?"selected":""}" data-profile-index="${u.index}">
                <div class="font-bold text-sm truncate" style="color:#f8f8f2;">${Xs(u.name)}</div>
                <div class="profile-npub">${Js(u.npub)}</div>
            </div>
        `).join(""),e.querySelectorAll("[data-profile-index]").forEach(u=>{u.addEventListener("click",()=>so(parseInt(u.dataset.profileIndex,10)))})),t&&(t.style.display=y.profiles.length===0?"block":"none");let i=y.selectedIndex!==null&&!y.showImport,a=y.showImport,c=!i&&!a;if(n&&(n.style.display=c?"block":"none"),o&&(o.style.display=i?"block":"none"),s&&(s.style.display=a?"block":"none"),i){let u=y.profiles.find(I=>I.index===y.selectedIndex),f=R("detail-name"),b=R("detail-npub"),x=R("detail-nsec"),A=R("toggle-nsec-btn");f&&(f.textContent=u?u.name:""),b&&(b.textContent=y.npubValue||""),x&&(x.textContent=y.nsecVisible?y.nsecValue:"\u2022".repeat(24)),A&&(A.textContent=y.nsecVisible?"Hide":"Reveal")}if(a){let u=R("import-data"),f=R("import-name"),b=R("import-error");u&&document.activeElement!==u&&(u.value=y.importData),f&&document.activeElement!==f&&(f.value=y.importName),b&&(b.textContent=y.importError,b.style.display=y.importError?"block":"none")}let l=R("toast");l&&(l.textContent=y.toast,l.style.display=y.toast?"block":"none")}async function oo(){let e=await Xn(),t=[];for(let r=0;r<e.length;r++){let n="";try{n=await z.runtime.sendMessage({kind:"getNpub",payload:r})}catch{}t.push({index:r,name:e[r],npub:n||""})}y.profiles=t}async function so(e){y.selectedIndex=e,y.nsecVisible=!1,y.nsecValue="",y.npubValue="",y.showImport=!1;let t=y.profiles.find(r=>r.index===e);y.npubValue=t?t.npub:"";try{let r=await z.runtime.sendMessage({kind:"getNsec",payload:e});y.nsecValue=r||""}catch{y.nsecValue=""}X()}function Qs(){y.nsecVisible=!y.nsecVisible,X()}async function ei(){y.npubValue&&(await navigator.clipboard.writeText(y.npubValue),wt("nPub copied"))}async function ti(){y.nsecValue&&(await navigator.clipboard.writeText(y.nsecValue),wt("nSec copied"),setTimeout(()=>{navigator.clipboard.writeText("").catch(()=>{})},3e4))}async function ri(){if(y.selectedIndex===null)return;let e=y.profiles.find(s=>s.index===y.selectedIndex);if(!e)return;let t={name:e.name,npub:y.npubValue,nsec:y.nsecValue,exportedAt:new Date().toISOString(),source:"NostrKey"},r=new Blob([JSON.stringify(t,null,2)],{type:"application/json"}),n=URL.createObjectURL(r),o=document.createElement("a");o.href=n,o.download=`nostrkey-${e.name.replace(/[^a-zA-Z0-9_-]/g,"_")}.json`,o.click(),URL.revokeObjectURL(n),wt("Exported")}function ni(){y.showImport=!0,y.selectedIndex=null,y.importData="",y.importName="",y.importError="",X()}function oi(){y.showImport=!1,y.importData="",y.importName="",y.importError="",X()}async function si(){y.importError="";let e=y.importData.trim();if(!e){y.importError="Please paste a JSON object or nsec string.",X();return}let t=y.importName.trim(),r="";try{let n=JSON.parse(e);r=n.nsec||n.privkey||n.privateKey||"",!t&&n.name&&(t=n.name)}catch{r=e}if(!r){y.importError='No private key found. Provide an nsec string or JSON with an "nsec" field.',X();return}if(!no(r)){y.importError="Invalid key format. Expected nsec1..., hex private key, or seed phrase.",X();return}t||(t="Imported Profile");try{let n=await ro();await eo(n,t),await to(n,r),await oo(),y.showImport=!1,y.importData="",y.importName="",y.importError="",await so(n),wt('Imported "'+t+'"')}catch(n){y.importError="Import failed: "+(n.message||"unknown error"),X()}}function ii(){R("close-btn")?.addEventListener("click",()=>window.close()),R("copy-npub-btn")?.addEventListener("click",ei),R("copy-nsec-btn")?.addEventListener("click",ti),R("toggle-nsec-btn")?.addEventListener("click",Qs),R("export-btn")?.addEventListener("click",ri),R("import-btn")?.addEventListener("click",ni),R("cancel-import-btn")?.addEventListener("click",oi),R("do-import-btn")?.addEventListener("click",si),R("import-data")?.addEventListener("input",e=>{y.importData=e.target.value}),R("import-name")?.addEventListener("input",e=>{y.importName=e.target.value})}async function ai(){await Jn();let e=await z.runtime.sendMessage({kind:"isEncrypted"}),t=R("vault-locked-gate"),r=R("vault-main-content");if(!e){t&&(t.style.display="block"),r&&(r.style.display="none"),R("gate-security-btn")?.addEventListener("click",()=>{let n=z.runtime.getURL("security/security.html");window.open(n,"nostrkey-options")});return}t&&(t.style.display="none"),r&&(r.style.display="block"),await oo(),ii(),X()}document.addEventListener("DOMContentLoaded",ai);})();
/*! Bundled license information:

@noble/curves/utils.js:
@noble/curves/abstract/modular.js:
@noble/curves/abstract/curve.js:
@noble/curves/abstract/weierstrass.js:
@noble/curves/secp256k1.js:
  (*! noble-curves - MIT License (c) 2022 Paul Miller (paulmillr.com) *)

@noble/hashes/utils.js:
  (*! noble-hashes - MIT License (c) 2022 Paul Miller (paulmillr.com) *)

@scure/base/index.js:
  (*! scure-base - MIT License (c) 2022 Paul Miller (paulmillr.com) *)

@scure/bip39/index.js:
  (*! scure-bip39 - MIT License (c) 2022 Patricio Palladino, Paul Miller (paulmillr.com) *)
*/
